using System;

namespace behaviac
{
	// Token: 0x0200227C RID: 8828
	public static class bt_AutoFight_AutoFight_Fight_Swordman_easy_Action
	{
		// Token: 0x06012E7C RID: 77436 RVA: 0x00593330 File Offset: 0x00591730
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Fight_Swordman_easy_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector.AddChild(sequence);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetId(2);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.HasEvents());
			DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7 decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node = new DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7();
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetId(7);
			sequence.AddChild(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(3);
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetId(8);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetId(9);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4.SetId(10);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11 action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node = new Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11();
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetId(11);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.HasEvents());
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.SetHasEvents(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.HasEvents() | sequence2.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(4);
			selector.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5.SetId(5);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5.HasEvents());
			DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6 decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2 = new DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6();
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetId(6);
			sequence3.AddChild(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2);
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(12);
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6.SetId(13);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7.SetId(15);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node16 action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node16();
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetId(16);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.HasEvents());
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.SetHasEvents(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.HasEvents() | sequence4.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(14);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node17 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node17();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8.SetId(17);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node8.HasEvents());
			DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node18 decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3 = new DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node18();
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetId(18);
			sequence5.AddChild(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3);
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(19);
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node20 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node20();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9.SetId(20);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node21 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node21();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10.SetId(21);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node10.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node22 action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node22();
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetId(22);
			sequence6.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.HasEvents());
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.SetHasEvents(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.HasEvents() | sequence6.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(23);
			selector.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node24 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node24();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11.SetId(24);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node11.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node25 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node12 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node25();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node12.SetId(25);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node12);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node12.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node26 action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node26();
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4.SetId(26);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node4.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node27 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node27();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13.SetId(27);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node13.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node28 action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node28();
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5.SetId(28);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(29);
			selector.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node30 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node14 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node30();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node14.SetId(30);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node14);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node14.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node31 condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node31();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15.SetId(31);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node15.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node34 action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node34();
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6.SetId(34);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_easy_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
