using System;

namespace behaviac
{
	// Token: 0x02002896 RID: 10390
	public static class bt_AutoFight_AutoFight_Swordman_Action
	{
		// Token: 0x06013A69 RID: 80489 RVA: 0x005DD9DC File Offset: 0x005DBDDC
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Swordman_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector.AddChild(sequence);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node2 condition_bt_AutoFight_AutoFight_Swordman_Action_node = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node2();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node.SetId(2);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node4 condition_bt_AutoFight_AutoFight_Swordman_Action_node2 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node4();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node2.SetId(4);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node2.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node88 condition_bt_AutoFight_AutoFight_Swordman_Action_node3 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node88();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node3.SetId(88);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node7 condition_bt_AutoFight_AutoFight_Swordman_Action_node4 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node7();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node4.SetId(7);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node4.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node8 action_bt_AutoFight_AutoFight_Swordman_Action_node = new Action_bt_AutoFight_AutoFight_Swordman_Action_node8();
			action_bt_AutoFight_AutoFight_Swordman_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node.SetId(8);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(20);
			selector.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node24 condition_bt_AutoFight_AutoFight_Swordman_Action_node5 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node24();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node5.SetId(24);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node5.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node21 condition_bt_AutoFight_AutoFight_Swordman_Action_node6 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node21();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node6.SetId(21);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node22 condition_bt_AutoFight_AutoFight_Swordman_Action_node7 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node22();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node7.SetId(22);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node23 action_bt_AutoFight_AutoFight_Swordman_Action_node2 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node23();
			action_bt_AutoFight_AutoFight_Swordman_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node2.SetId(23);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(13);
			selector.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node14 condition_bt_AutoFight_AutoFight_Swordman_Action_node8 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node14();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node8.SetId(14);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node8.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node17 condition_bt_AutoFight_AutoFight_Swordman_Action_node9 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node17();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node9.SetId(17);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node47 condition_bt_AutoFight_AutoFight_Swordman_Action_node10 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node47();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node10.SetId(47);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node10.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node49 action_bt_AutoFight_AutoFight_Swordman_Action_node3 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node49();
			action_bt_AutoFight_AutoFight_Swordman_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node3.SetId(49);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(25);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node26 condition_bt_AutoFight_AutoFight_Swordman_Action_node11 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node26();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node11.SetId(26);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node11.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node27 condition_bt_AutoFight_AutoFight_Swordman_Action_node12 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node27();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node12.SetId(27);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node12.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node28 condition_bt_AutoFight_AutoFight_Swordman_Action_node13 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node28();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node13.SetId(28);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node13);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node13.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node29 action_bt_AutoFight_AutoFight_Swordman_Action_node4 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node29();
			action_bt_AutoFight_AutoFight_Swordman_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node4.SetId(29);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(3);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node5 condition_bt_AutoFight_AutoFight_Swordman_Action_node14 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node5();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node14.SetId(5);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node14.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node6 condition_bt_AutoFight_AutoFight_Swordman_Action_node15 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node6();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node15.SetId(6);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node15.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node9 condition_bt_AutoFight_AutoFight_Swordman_Action_node16 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node9();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node16.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node16.SetId(9);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node16);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node16.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node10 action_bt_AutoFight_AutoFight_Swordman_Action_node5 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node10();
			action_bt_AutoFight_AutoFight_Swordman_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node5.SetId(10);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(15);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node16 condition_bt_AutoFight_AutoFight_Swordman_Action_node17 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node16();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node17.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node17.SetId(16);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node17.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(18);
			sequence6.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node19 condition_bt_AutoFight_AutoFight_Swordman_Action_node18 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node19();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node18.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node18.SetId(19);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node18);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node18.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node11 condition_bt_AutoFight_AutoFight_Swordman_Action_node19 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node11();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node19.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node19.SetId(11);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node19.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node12 action_bt_AutoFight_AutoFight_Swordman_Action_node6 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node12();
			action_bt_AutoFight_AutoFight_Swordman_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node6.SetId(12);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node6.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | sequence7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(30);
			selector.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node31 condition_bt_AutoFight_AutoFight_Swordman_Action_node20 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node31();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node20.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node20.SetId(31);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node20);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node20.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node32 condition_bt_AutoFight_AutoFight_Swordman_Action_node21 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node32();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node21.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node21.SetId(32);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node21);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node21.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node33 condition_bt_AutoFight_AutoFight_Swordman_Action_node22 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node33();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node22.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node22.SetId(33);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node22);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node22.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node34 action_bt_AutoFight_AutoFight_Swordman_Action_node7 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node34();
			action_bt_AutoFight_AutoFight_Swordman_Action_node7.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node7.SetId(34);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node7);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(35);
			selector.AddChild(sequence9);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node36 condition_bt_AutoFight_AutoFight_Swordman_Action_node23 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node36();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node23.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node23.SetId(36);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node23);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node23.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node37 condition_bt_AutoFight_AutoFight_Swordman_Action_node24 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node37();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node24.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node24.SetId(37);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node24);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node24.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node38 condition_bt_AutoFight_AutoFight_Swordman_Action_node25 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node38();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node25.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node25.SetId(38);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node25);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node25.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node39 action_bt_AutoFight_AutoFight_Swordman_Action_node8 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node39();
			action_bt_AutoFight_AutoFight_Swordman_Action_node8.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node8.SetId(39);
			sequence9.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node8);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(83);
			selector.AddChild(sequence10);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node84 condition_bt_AutoFight_AutoFight_Swordman_Action_node26 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node84();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node26.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node26.SetId(84);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node26);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node26.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node85 condition_bt_AutoFight_AutoFight_Swordman_Action_node27 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node85();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node27.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node27.SetId(85);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node27);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node27.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node87 action_bt_AutoFight_AutoFight_Swordman_Action_node9 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node87();
			action_bt_AutoFight_AutoFight_Swordman_Action_node9.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node9.SetId(87);
			sequence10.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node9);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(40);
			selector.AddChild(sequence11);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node41 condition_bt_AutoFight_AutoFight_Swordman_Action_node28 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node41();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node28.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node28.SetId(41);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node28);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node28.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node42 condition_bt_AutoFight_AutoFight_Swordman_Action_node29 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node42();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node29.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node29.SetId(42);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node29);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node29.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node52 condition_bt_AutoFight_AutoFight_Swordman_Action_node30 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node52();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node30.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node30.SetId(52);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node30);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node30.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node44 action_bt_AutoFight_AutoFight_Swordman_Action_node10 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node44();
			action_bt_AutoFight_AutoFight_Swordman_Action_node10.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node10.SetId(44);
			sequence11.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node10);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node10.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(43);
			selector.AddChild(sequence12);
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node45 condition_bt_AutoFight_AutoFight_Swordman_Action_node31 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node45();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node31.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node31.SetId(45);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node31);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node31.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Action_node46 condition_bt_AutoFight_AutoFight_Swordman_Action_node32 = new Condition_bt_AutoFight_AutoFight_Swordman_Action_node46();
			condition_bt_AutoFight_AutoFight_Swordman_Action_node32.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Action_node32.SetId(46);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Action_node32);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Action_node32.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Action_node48 action_bt_AutoFight_AutoFight_Swordman_Action_node11 = new Action_bt_AutoFight_AutoFight_Swordman_Action_node48();
			action_bt_AutoFight_AutoFight_Swordman_Action_node11.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Action_node11.SetId(48);
			sequence12.AddChild(action_bt_AutoFight_AutoFight_Swordman_Action_node11);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Action_node11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
