using System;

namespace behaviac
{
	// Token: 0x020029DC RID: 10716
	public static class bt_AutoFight_AutoFight_Swordman_Zhengui_Action
	{
		// Token: 0x06013CEC RID: 81132 RVA: 0x005EC218 File Offset: 0x005EA618
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Swordman_Zhengui_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(3);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(2);
			selector.AddChild(sequence);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node.SetId(6);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node0 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node0();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2.SetId(0);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3.SetId(7);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node.SetId(8);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(4);
			selector.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4.SetId(5);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(10);
			sequence2.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5.SetId(11);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6.SetId(12);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7.SetId(13);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2.SetId(14);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node2.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | sequence3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(24);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8.SetId(29);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9.SetId(30);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10.SetId(31);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11.SetId(32);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3.SetId(33);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(92);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node113 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node113();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12.SetId(113);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node114 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node114();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13.SetId(114);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node125 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node125();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14.SetId(125);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node115 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node115();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4.SetId(115);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(22);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node117 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node117();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15.SetId(117);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node118 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node118();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16.SetId(118);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node119 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node119();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17.SetId(119);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node120 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node120();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18.SetId(120);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node121 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node121();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5.SetId(121);
			sequence6.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(20);
			selector.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19.SetId(23);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(25);
			sequence7.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20.SetId(26);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21.SetId(27);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6.SetId(28);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node6.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | sequence8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(116);
			selector.AddChild(sequence9);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node127 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node127();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22.SetId(127);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node122 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node122();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23.SetId(122);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node23.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node123 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node24 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node123();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node24.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node24.SetId(123);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node24);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node24.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node126 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node25 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node126();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node25.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node25.SetId(126);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node25);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node25.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node124 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node124();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7.SetId(124);
			sequence9.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node128 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node128();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8.SetId(128);
			sequence9.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(69);
			selector.AddChild(sequence10);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26.SetId(70);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node26.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(72);
			sequence10.AddChild(sequence11);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node73 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node73();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27.SetId(73);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node27.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node74 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node74();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28.SetId(74);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node28.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node75 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node75();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9.SetId(75);
			sequence11.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | sequence11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(15);
			selector.AddChild(sequence12);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29.SetId(16);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node29.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(18);
			sequence12.AddChild(sequence13);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30.SetId(19);
			sequence13.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node30.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31.SetId(21);
			sequence13.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node31.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10.SetId(39);
			sequence13.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node10.HasEvents());
			sequence12.SetHasEvents(sequence12.HasEvents() | sequence13.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(34);
			selector.AddChild(sequence14);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32.SetId(35);
			sequence14.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node32.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33.SetId(52);
			sequence14.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node33.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node88 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node34 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node88();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node34.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node34.SetId(88);
			sequence14.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node34);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node34.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node89 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node89();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11.SetId(89);
			sequence14.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(107);
			selector.AddChild(sequence15);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node108 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node108();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35.SetId(108);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node35.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node109 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node36 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node109();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node36.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node36.SetId(109);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node36);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node36.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node110 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node110();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37.SetId(110);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node111 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node111();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38.SetId(111);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node112 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node112();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12.SetId(112);
			sequence15.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node12.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(101);
			selector.AddChild(sequence16);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node102 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node102();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39.SetId(102);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node39.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node103 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node103();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40.SetId(103);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node104 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node104();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41.SetId(104);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node105 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node42 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node105();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node42.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node42.SetId(105);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node42);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node42.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node106 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node106();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13.SetId(106);
			sequence16.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node13.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence16.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(71);
			selector.AddChild(sequence17);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node90 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node90();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43.SetId(90);
			sequence17.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node91 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node91();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44.SetId(91);
			sequence17.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node99 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node99();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45.SetId(99);
			sequence17.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node100 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node100();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14.SetId(100);
			sequence17.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node14.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence17.HasEvents());
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(36);
			selector.AddChild(sequence18);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node37();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46.SetId(37);
			sequence18.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node38();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47.SetId(38);
			sequence18.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node48 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node40();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node48.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node48.SetId(40);
			sequence18.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node48);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node48.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node41();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15.SetId(41);
			sequence18.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node15.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence18.HasEvents());
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(42);
			selector.AddChild(sequence19);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node49 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node44();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node49.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node49.SetId(44);
			sequence19.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node49);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node49.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node50 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node43();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node50.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node50.SetId(43);
			sequence19.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node50);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node50.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node51 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node9();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node51.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node51.SetId(9);
			sequence19.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node51);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node51.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node45();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52.SetId(45);
			sequence19.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node52.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node46();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16.SetId(46);
			sequence19.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node16.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence19.HasEvents());
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(53);
			selector.AddChild(sequence20);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node53 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node53.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node53.SetId(54);
			sequence20.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node53);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node53.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54.SetId(55);
			sequence20.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node54.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55.SetId(57);
			sequence20.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node55.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17.SetId(58);
			sequence20.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node17.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence20.HasEvents());
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(93);
			selector.AddChild(sequence21);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node94 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node94();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56.SetId(94);
			sequence21.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node95 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node95();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57.SetId(95);
			sequence21.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node57.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node96 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node96();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58.SetId(96);
			sequence21.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node58.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node97 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node59 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node97();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node59.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node59.SetId(97);
			sequence21.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node59);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node59.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node98 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node98();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18.SetId(98);
			sequence21.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node18.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence21.HasEvents());
			Sequence sequence22 = new Sequence();
			sequence22.SetClassNameString("Sequence");
			sequence22.SetId(59);
			selector.AddChild(sequence22);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60.SetId(60);
			sequence22.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60);
			sequence22.SetHasEvents(sequence22.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node60.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61.SetId(61);
			sequence22.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61);
			sequence22.SetHasEvents(sequence22.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node61.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node56();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62.SetId(56);
			sequence22.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62);
			sequence22.SetHasEvents(sequence22.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19.SetId(64);
			sequence22.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19);
			sequence22.SetHasEvents(sequence22.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node19.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence22.HasEvents());
			Sequence sequence23 = new Sequence();
			sequence23.SetClassNameString("Sequence");
			sequence23.SetId(17);
			selector.AddChild(sequence23);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node62();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63.SetId(62);
			sequence23.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node63();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64.SetId(63);
			sequence23.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node64.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65.SetId(65);
			sequence23.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node65.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66.SetId(66);
			sequence23.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node66.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20.SetId(67);
			sequence23.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20);
			sequence23.SetHasEvents(sequence23.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node20.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence23.HasEvents());
			Sequence sequence24 = new Sequence();
			sequence24.SetClassNameString("Sequence");
			sequence24.SetId(130);
			selector.AddChild(sequence24);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node131 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node131();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67.SetId(131);
			sequence24.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node67.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node132 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node68 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node132();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node68.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node68.SetId(132);
			sequence24.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node68);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node68.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node133 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node69 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node133();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node69.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node69.SetId(133);
			sequence24.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node69);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node69.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node134 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node134();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70.SetId(134);
			sequence24.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node70.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node135 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node135();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21.SetId(135);
			sequence24.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21);
			sequence24.SetHasEvents(sequence24.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node21.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence24.HasEvents());
			Sequence sequence25 = new Sequence();
			sequence25.SetClassNameString("Sequence");
			sequence25.SetId(78);
			selector.AddChild(sequence25);
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node80 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node71 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node80();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node71.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node71.SetId(80);
			sequence25.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node71);
			sequence25.SetHasEvents(sequence25.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node71.HasEvents());
			Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node81 condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node72 = new Condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node81();
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node72.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node72.SetId(81);
			sequence25.AddChild(condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node72);
			sequence25.SetHasEvents(sequence25.HasEvents() | condition_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node72.HasEvents());
			Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47 action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22 = new Action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node47();
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22.SetId(47);
			sequence25.AddChild(action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22);
			sequence25.SetHasEvents(sequence25.HasEvents() | action_bt_AutoFight_AutoFight_Swordman_Zhengui_Action_node22.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence25.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
