using System;

namespace behaviac
{
	// Token: 0x02001D74 RID: 7540
	public static class bt_APC_APC_jiqingjieshuoyuan_Action
	{
		// Token: 0x060124A5 RID: 74917 RVA: 0x00555FF4 File Offset: 0x005543F4
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("APC/APC_jiqingjieshuoyuan_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector.AddChild(sequence);
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node.SetId(2);
			sequence.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2.SetId(3);
			sequence.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node2.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3.SetId(4);
			sequence.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node3.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4.SetId(5);
			sequence.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node4.HasEvents());
			Action_bt_APC_APC_jiqingjieshuoyuan_Action_node6 action_bt_APC_APC_jiqingjieshuoyuan_Action_node = new Action_bt_APC_APC_jiqingjieshuoyuan_Action_node6();
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node.SetClassNameString("Action");
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node.SetId(6);
			sequence.AddChild(action_bt_APC_APC_jiqingjieshuoyuan_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_APC_APC_jiqingjieshuoyuan_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(7);
			selector.AddChild(sequence2);
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5.SetId(8);
			sequence2.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node5.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node6 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node6.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node6.SetId(9);
			sequence2.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node6.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node7 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node7.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node7.SetId(10);
			sequence2.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node7.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8.SetId(11);
			sequence2.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node8.HasEvents());
			Action_bt_APC_APC_jiqingjieshuoyuan_Action_node12 action_bt_APC_APC_jiqingjieshuoyuan_Action_node2 = new Action_bt_APC_APC_jiqingjieshuoyuan_Action_node12();
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node2.SetClassNameString("Action");
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node2.SetId(12);
			sequence2.AddChild(action_bt_APC_APC_jiqingjieshuoyuan_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_APC_APC_jiqingjieshuoyuan_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(13);
			selector.AddChild(sequence3);
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9.SetId(14);
			sequence3.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node9.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10.SetId(15);
			sequence3.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node10.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node16 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node16();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11.SetId(16);
			sequence3.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node11.HasEvents());
			Action_bt_APC_APC_jiqingjieshuoyuan_Action_node18 action_bt_APC_APC_jiqingjieshuoyuan_Action_node3 = new Action_bt_APC_APC_jiqingjieshuoyuan_Action_node18();
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node3.SetClassNameString("Action");
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node3.SetId(18);
			sequence3.AddChild(action_bt_APC_APC_jiqingjieshuoyuan_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_APC_APC_jiqingjieshuoyuan_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(17);
			selector.AddChild(sequence4);
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node19 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node12 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node19();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node12.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node12.SetId(19);
			sequence4.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node12.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(20);
			sequence4.AddChild(selector2);
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node21 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node13 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node21();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node13.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node13.SetId(21);
			selector2.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node13);
			selector2.SetHasEvents(selector2.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node13.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(22);
			selector2.AddChild(sequence5);
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node23 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node23();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14.SetId(23);
			sequence5.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node14.HasEvents());
			Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node24 condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15 = new Condition_bt_APC_APC_jiqingjieshuoyuan_Action_node24();
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15.SetClassNameString("Condition");
			condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15.SetId(24);
			sequence5.AddChild(condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_APC_APC_jiqingjieshuoyuan_Action_node15.HasEvents());
			Action_bt_APC_APC_jiqingjieshuoyuan_Action_node25 action_bt_APC_APC_jiqingjieshuoyuan_Action_node4 = new Action_bt_APC_APC_jiqingjieshuoyuan_Action_node25();
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node4.SetClassNameString("Action");
			action_bt_APC_APC_jiqingjieshuoyuan_Action_node4.SetId(25);
			sequence5.AddChild(action_bt_APC_APC_jiqingjieshuoyuan_Action_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_APC_APC_jiqingjieshuoyuan_Action_node4.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence5.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | selector2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
