using System;

namespace behaviac
{
	// Token: 0x02001D2B RID: 7467
	public static class bt_APC_APC_Guiqi2_Action
	{
		// Token: 0x06012419 RID: 74777 RVA: 0x00552620 File Offset: 0x00550A20
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("APC/APC_Guiqi2_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(13);
			selector.AddChild(sequence);
			Condition_bt_APC_APC_Guiqi2_Action_node2 condition_bt_APC_APC_Guiqi2_Action_node = new Condition_bt_APC_APC_Guiqi2_Action_node2();
			condition_bt_APC_APC_Guiqi2_Action_node.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node.SetId(2);
			sequence.AddChild(condition_bt_APC_APC_Guiqi2_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node8 condition_bt_APC_APC_Guiqi2_Action_node2 = new Condition_bt_APC_APC_Guiqi2_Action_node8();
			condition_bt_APC_APC_Guiqi2_Action_node2.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node2.SetId(8);
			sequence.AddChild(condition_bt_APC_APC_Guiqi2_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node2.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node3 condition_bt_APC_APC_Guiqi2_Action_node3 = new Condition_bt_APC_APC_Guiqi2_Action_node3();
			condition_bt_APC_APC_Guiqi2_Action_node3.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node3.SetId(3);
			sequence.AddChild(condition_bt_APC_APC_Guiqi2_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node3.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node16 condition_bt_APC_APC_Guiqi2_Action_node4 = new Condition_bt_APC_APC_Guiqi2_Action_node16();
			condition_bt_APC_APC_Guiqi2_Action_node4.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node4.SetId(16);
			sequence.AddChild(condition_bt_APC_APC_Guiqi2_Action_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node4.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node5 action_bt_APC_APC_Guiqi2_Action_node = new Action_bt_APC_APC_Guiqi2_Action_node5();
			action_bt_APC_APC_Guiqi2_Action_node.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node.SetId(5);
			sequence.AddChild(action_bt_APC_APC_Guiqi2_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(72);
			selector.AddChild(sequence2);
			Condition_bt_APC_APC_Guiqi2_Action_node73 condition_bt_APC_APC_Guiqi2_Action_node5 = new Condition_bt_APC_APC_Guiqi2_Action_node73();
			condition_bt_APC_APC_Guiqi2_Action_node5.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node5.SetId(73);
			sequence2.AddChild(condition_bt_APC_APC_Guiqi2_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node5.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node74 condition_bt_APC_APC_Guiqi2_Action_node6 = new Condition_bt_APC_APC_Guiqi2_Action_node74();
			condition_bt_APC_APC_Guiqi2_Action_node6.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node6.SetId(74);
			sequence2.AddChild(condition_bt_APC_APC_Guiqi2_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node6.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node75 action_bt_APC_APC_Guiqi2_Action_node2 = new Action_bt_APC_APC_Guiqi2_Action_node75();
			action_bt_APC_APC_Guiqi2_Action_node2.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node2.SetId(75);
			sequence2.AddChild(action_bt_APC_APC_Guiqi2_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(11);
			selector.AddChild(sequence3);
			Condition_bt_APC_APC_Guiqi2_Action_node15 condition_bt_APC_APC_Guiqi2_Action_node7 = new Condition_bt_APC_APC_Guiqi2_Action_node15();
			condition_bt_APC_APC_Guiqi2_Action_node7.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node7.SetId(15);
			sequence3.AddChild(condition_bt_APC_APC_Guiqi2_Action_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node7.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node23 condition_bt_APC_APC_Guiqi2_Action_node8 = new Condition_bt_APC_APC_Guiqi2_Action_node23();
			condition_bt_APC_APC_Guiqi2_Action_node8.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node8.SetId(23);
			sequence3.AddChild(condition_bt_APC_APC_Guiqi2_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node8.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node26 action_bt_APC_APC_Guiqi2_Action_node3 = new Action_bt_APC_APC_Guiqi2_Action_node26();
			action_bt_APC_APC_Guiqi2_Action_node3.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node3.SetId(26);
			sequence3.AddChild(action_bt_APC_APC_Guiqi2_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(71);
			selector.AddChild(sequence4);
			Condition_bt_APC_APC_Guiqi2_Action_node90 condition_bt_APC_APC_Guiqi2_Action_node9 = new Condition_bt_APC_APC_Guiqi2_Action_node90();
			condition_bt_APC_APC_Guiqi2_Action_node9.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node9.SetId(90);
			sequence4.AddChild(condition_bt_APC_APC_Guiqi2_Action_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node9.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node91 condition_bt_APC_APC_Guiqi2_Action_node10 = new Condition_bt_APC_APC_Guiqi2_Action_node91();
			condition_bt_APC_APC_Guiqi2_Action_node10.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node10.SetId(91);
			sequence4.AddChild(condition_bt_APC_APC_Guiqi2_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node10.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node99 condition_bt_APC_APC_Guiqi2_Action_node11 = new Condition_bt_APC_APC_Guiqi2_Action_node99();
			condition_bt_APC_APC_Guiqi2_Action_node11.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node11.SetId(99);
			sequence4.AddChild(condition_bt_APC_APC_Guiqi2_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node11.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node100 action_bt_APC_APC_Guiqi2_Action_node4 = new Action_bt_APC_APC_Guiqi2_Action_node100();
			action_bt_APC_APC_Guiqi2_Action_node4.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node4.SetId(100);
			sequence4.AddChild(action_bt_APC_APC_Guiqi2_Action_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(59);
			selector.AddChild(sequence5);
			Condition_bt_APC_APC_Guiqi2_Action_node60 condition_bt_APC_APC_Guiqi2_Action_node12 = new Condition_bt_APC_APC_Guiqi2_Action_node60();
			condition_bt_APC_APC_Guiqi2_Action_node12.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node12.SetId(60);
			sequence5.AddChild(condition_bt_APC_APC_Guiqi2_Action_node12);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node12.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node61 condition_bt_APC_APC_Guiqi2_Action_node13 = new Condition_bt_APC_APC_Guiqi2_Action_node61();
			condition_bt_APC_APC_Guiqi2_Action_node13.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node13.SetId(61);
			sequence5.AddChild(condition_bt_APC_APC_Guiqi2_Action_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node13.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node56 condition_bt_APC_APC_Guiqi2_Action_node14 = new Condition_bt_APC_APC_Guiqi2_Action_node56();
			condition_bt_APC_APC_Guiqi2_Action_node14.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node14.SetId(56);
			sequence5.AddChild(condition_bt_APC_APC_Guiqi2_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node14.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node64 action_bt_APC_APC_Guiqi2_Action_node5 = new Action_bt_APC_APC_Guiqi2_Action_node64();
			action_bt_APC_APC_Guiqi2_Action_node5.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node5.SetId(64);
			sequence5.AddChild(action_bt_APC_APC_Guiqi2_Action_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(53);
			selector.AddChild(sequence6);
			Condition_bt_APC_APC_Guiqi2_Action_node54 condition_bt_APC_APC_Guiqi2_Action_node15 = new Condition_bt_APC_APC_Guiqi2_Action_node54();
			condition_bt_APC_APC_Guiqi2_Action_node15.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node15.SetId(54);
			sequence6.AddChild(condition_bt_APC_APC_Guiqi2_Action_node15);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node15.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node55 condition_bt_APC_APC_Guiqi2_Action_node16 = new Condition_bt_APC_APC_Guiqi2_Action_node55();
			condition_bt_APC_APC_Guiqi2_Action_node16.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node16.SetId(55);
			sequence6.AddChild(condition_bt_APC_APC_Guiqi2_Action_node16);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node16.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node57 condition_bt_APC_APC_Guiqi2_Action_node17 = new Condition_bt_APC_APC_Guiqi2_Action_node57();
			condition_bt_APC_APC_Guiqi2_Action_node17.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node17.SetId(57);
			sequence6.AddChild(condition_bt_APC_APC_Guiqi2_Action_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node17.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node58 action_bt_APC_APC_Guiqi2_Action_node6 = new Action_bt_APC_APC_Guiqi2_Action_node58();
			action_bt_APC_APC_Guiqi2_Action_node6.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node6.SetId(58);
			sequence6.AddChild(action_bt_APC_APC_Guiqi2_Action_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(1);
			selector.AddChild(sequence7);
			Condition_bt_APC_APC_Guiqi2_Action_node4 condition_bt_APC_APC_Guiqi2_Action_node18 = new Condition_bt_APC_APC_Guiqi2_Action_node4();
			condition_bt_APC_APC_Guiqi2_Action_node18.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node18.SetId(4);
			sequence7.AddChild(condition_bt_APC_APC_Guiqi2_Action_node18);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node18.HasEvents());
			Condition_bt_APC_APC_Guiqi2_Action_node9 condition_bt_APC_APC_Guiqi2_Action_node19 = new Condition_bt_APC_APC_Guiqi2_Action_node9();
			condition_bt_APC_APC_Guiqi2_Action_node19.SetClassNameString("Condition");
			condition_bt_APC_APC_Guiqi2_Action_node19.SetId(9);
			sequence7.AddChild(condition_bt_APC_APC_Guiqi2_Action_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_APC_APC_Guiqi2_Action_node19.HasEvents());
			Action_bt_APC_APC_Guiqi2_Action_node10 action_bt_APC_APC_Guiqi2_Action_node7 = new Action_bt_APC_APC_Guiqi2_Action_node10();
			action_bt_APC_APC_Guiqi2_Action_node7.SetClassNameString("Action");
			action_bt_APC_APC_Guiqi2_Action_node7.SetId(10);
			sequence7.AddChild(action_bt_APC_APC_Guiqi2_Action_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_APC_APC_Guiqi2_Action_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
