using System;

namespace behaviac
{
	// Token: 0x020020B9 RID: 8377
	public static class bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action
	{
		// Token: 0x06012B09 RID: 76553 RVA: 0x0057CA24 File Offset: 0x0057AE24
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Fight_Gungirl_veryhard_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector.AddChild(sequence);
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node.SetId(2);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2.SetId(3);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node.SetId(4);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2.SetId(5);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(6);
			selector.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3.SetId(7);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4.SetId(8);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3.SetId(9);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node3.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4.SetId(10);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(11);
			selector.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5.SetId(12);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node13 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node13();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6.SetId(13);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node14 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node14();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5.SetId(14);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node5.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node15 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node15();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6.SetId(15);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(16);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node17 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node17();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7.SetId(17);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node18 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node18();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8.SetId(18);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node19 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node19();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7.SetId(19);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node20 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node20();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8.SetId(20);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(21);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node22 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node22();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9.SetId(22);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node23 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node23();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10.SetId(23);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node24 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node24();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9.SetId(24);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node9.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node25 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node25();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10.SetId(25);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node10.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(26);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node27 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node27();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11.SetId(27);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node28 condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12 = new Condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node28();
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12.SetId(28);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node12.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node30 action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11 = new Action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node30();
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11.SetId(30);
			sequence6.AddChild(action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Gungirl_veryhard_Action_node11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
