using System;

namespace behaviac
{
	// Token: 0x02001F24 RID: 7972
	public static class bt_AutoFight_AutoFight_Fightergirl_qigong_Action
	{
		// Token: 0x060127EC RID: 75756 RVA: 0x005691F8 File Offset: 0x005675F8
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Fightergirl_qigong_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(3);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(2);
			selector.AddChild(sequence);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node.SetId(7);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2.SetId(6);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node.SetId(8);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(30);
			selector.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node40 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node40();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3.SetId(40);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node39 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node39();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4.SetId(39);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node1 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node1();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5.SetId(1);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node41 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node41();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2.SetId(41);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(42);
			selector.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node43 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node43();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6.SetId(43);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node44 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node44();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7.SetId(44);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node45 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node45();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8.SetId(45);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node46 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node46();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3.SetId(46);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(4);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9.SetId(5);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10.SetId(11);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11.SetId(12);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12.SetId(13);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4.SetId(14);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(69);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13.SetId(18);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node13.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node73 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node73();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14.SetId(73);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node14.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node74 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node74();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15.SetId(74);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node75 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node75();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5.SetId(75);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(20);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16.SetId(23);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node17 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node17.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node17.SetId(26);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node17.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18.SetId(27);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node18.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6.SetId(28);
			sequence6.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(21);
			selector.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19.SetId(22);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node20 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node20.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node20.SetId(24);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node20);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node20.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node21 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node21.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node21.SetId(25);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node21);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node21.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7.SetId(29);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(9);
			selector.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node15();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22.SetId(15);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node22.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23.SetId(10);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node23.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24.SetId(32);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node24.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node16();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8.SetId(16);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(36);
			selector.AddChild(sequence9);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25.SetId(31);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node25.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node38 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node38();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26.SetId(38);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node26.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27.SetId(37);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node27.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9.SetId(33);
			sequence9.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(53);
			selector.AddChild(sequence10);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node55 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node55();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28.SetId(55);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node28.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node54 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node54();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29.SetId(54);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node29.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node57 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node30 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node57();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node30.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node30.SetId(57);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node30);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node30.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node58 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node58();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10.SetId(58);
			sequence10.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node10.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(47);
			selector.AddChild(sequence11);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node49 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node49();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31.SetId(49);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node31.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node48 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node48();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32.SetId(48);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node32.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node52 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node52();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33.SetId(52);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node33.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node50 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node50();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34.SetId(50);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node51 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node51();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11.SetId(51);
			sequence11.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(17);
			selector.AddChild(sequence12);
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node62 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node35 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node62();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node35.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node35.SetId(62);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node35);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node35.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node0 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node36 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node0();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node36.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node36.SetId(0);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node36);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node36.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19 condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37 = new Condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node19();
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37.SetId(19);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node37.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34 action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12 = new Action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node34();
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12.SetId(34);
			sequence12.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_qigong_Action_node12.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
