using System;

namespace behaviac
{
	// Token: 0x0200246F RID: 9327
	public static class bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action
	{
		// Token: 0x0601322E RID: 78382 RVA: 0x005AD844 File Offset: 0x005ABC44
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Fight_Swordman_veryhard_Action");
			bt.IsFSM = false;
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			bt.AddChild(sequence);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(3);
			sequence.AddChild(selector);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(4);
			selector.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetId(5);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.HasEvents());
			DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9 decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node = new DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9();
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetId(9);
			sequence2.AddChild(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(10);
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetId(11);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetId(12);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4.SetId(13);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14 action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node = new Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14();
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetId(14);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.HasEvents());
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.SetHasEvents(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.HasEvents() | sequence3.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(15);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5.SetId(16);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5.HasEvents());
			DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17 decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2 = new DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17();
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetId(17);
			sequence4.AddChild(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2);
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(18);
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node19 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node19();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6.SetId(19);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node21 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node7 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node21();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node7.SetId(21);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node22 action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node22();
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetId(22);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.HasEvents());
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.SetHasEvents(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.HasEvents() | sequence5.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(1);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node2();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8.SetId(2);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8.HasEvents());
			DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6 decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3 = new DecoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node6();
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetId(6);
			sequence6.AddChild(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(7);
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node8();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9.SetId(8);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node42 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node10 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node42();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node10.SetId(42);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node10);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node10.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node43 action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node43();
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetId(43);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.HasEvents());
			decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.SetHasEvents(decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.HasEvents() | sequence7.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | decoratorAlwaysSuccess_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(36);
			selector.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node37 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node37();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11.SetId(37);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node11.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node38 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node38();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12.SetId(38);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node12.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node39 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node39();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13.SetId(39);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node13.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node40 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node40();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14.SetId(40);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node14.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node41 action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node41();
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4.SetId(41);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(62);
			selector.AddChild(sequence9);
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node63 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node15 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node63();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node15.SetId(63);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node15);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node15.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node65 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node65();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16.SetId(65);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node16.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node67 condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17 = new Condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node67();
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17.SetId(67);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node17.HasEvents());
			Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node68 action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5 = new Action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node68();
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5.SetId(68);
			sequence9.AddChild(action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_AutoFight_AutoFight_Fight_Swordman_veryhard_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | selector.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | sequence.HasEvents());
			return true;
		}
	}
}
