using System;

namespace behaviac
{
	// Token: 0x02002513 RID: 9491
	public static class bt_AutoFight_AutoFight_Gungirl_Manyou_Action
	{
		// Token: 0x06013370 RID: 78704 RVA: 0x005B455C File Offset: 0x005B295C
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Gungirl_Manyou_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(83);
			selector.AddChild(sequence);
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node85 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node85();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node.SetId(85);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node84 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node84();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node.SetId(84);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node86 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node86();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2.SetId(86);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node87 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node87();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2.SetId(87);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(88);
			selector.AddChild(sequence2);
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node89 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node89();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3.SetId(89);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node90 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node90();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3.SetId(90);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node91 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node91();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4.SetId(91);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node92 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node92();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4.SetId(92);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(3);
			selector.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node94 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node94();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5.SetId(94);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node95 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node95();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6.SetId(95);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node96 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node96();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7.SetId(96);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node97 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node97();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5.SetId(97);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(1);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node2();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8.SetId(2);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node93 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node93();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9.SetId(93);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10.SetId(7);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6.SetId(8);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(20);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11.SetId(24);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12.SetId(21);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13.SetId(22);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7.SetId(23);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(25);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14.SetId(26);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15.SetId(27);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16.SetId(28);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8.SetId(29);
			sequence6.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(30);
			selector.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17.SetId(31);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18.SetId(32);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19.SetId(33);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9.SetId(34);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(35);
			selector.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20.SetId(36);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21.SetId(37);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22.SetId(38);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10.SetId(39);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(52);
			selector.AddChild(sequence9);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node54 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node54();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23.SetId(54);
			sequence9.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node23.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(55);
			sequence9.AddChild(selector2);
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(56);
			selector2.AddChild(sequence10);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node57 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node57();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24.SetId(57);
			sequence10.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node24.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node58 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node58();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11.SetId(58);
			sequence10.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(59);
			selector2.AddChild(sequence11);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node60 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node25 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node60();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node25.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node25.SetId(60);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node25);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node25.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node61 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node61();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26.SetId(61);
			sequence11.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node26.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node62 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node62();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12.SetId(62);
			sequence11.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(63);
			selector2.AddChild(sequence12);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node64 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node64();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27.SetId(64);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node27.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node65 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node65();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28.SetId(65);
			sequence12.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node28.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node66 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node66();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13.SetId(66);
			sequence12.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node13.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selector2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(77);
			selector.AddChild(sequence13);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node79 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node79();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29.SetId(79);
			sequence13.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node29.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node80 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node30 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node80();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node30.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node30.SetId(80);
			sequence13.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node30);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node30.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node81 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node81();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31.SetId(81);
			sequence13.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node31.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node82 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node82();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14.SetId(82);
			sequence13.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence13.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(40);
			selector.AddChild(sequence14);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32.SetId(41);
			sequence14.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node32.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33.SetId(42);
			sequence14.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node33.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node4();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34.SetId(4);
			sequence14.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node34.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15.SetId(44);
			sequence14.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(43);
			selector.AddChild(sequence15);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node35 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node35.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node35.SetId(45);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node35);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node35.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36.SetId(46);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node36.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node5();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37.SetId(5);
			sequence15.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node37.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16.SetId(48);
			sequence15.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(6);
			selector.AddChild(sequence16);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node9();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38.SetId(9);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node38.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node10();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39.SetId(10);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node39.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node40 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node11();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node40.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node40.SetId(11);
			sequence16.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node40);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node40.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node12();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17.SetId(12);
			sequence16.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence16.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(13);
			selector.AddChild(sequence17);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node14();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41.SetId(14);
			sequence17.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node41.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node15();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42.SetId(15);
			sequence17.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node42.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node43 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node17();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node43.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node43.SetId(17);
			sequence17.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node43);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node43.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node16();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18.SetId(16);
			sequence17.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node18.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence17.HasEvents());
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(18);
			selector.AddChild(sequence18);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44.SetId(19);
			sequence18.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node44.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45.SetId(47);
			sequence18.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node45.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46.SetId(49);
			sequence18.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node46.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19.SetId(50);
			sequence18.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node19.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence18.HasEvents());
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(51);
			selector.AddChild(sequence19);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47.SetId(53);
			sequence19.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node47.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node67 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node67();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48.SetId(67);
			sequence19.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node48.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node69 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node69();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20.SetId(69);
			sequence19.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node20.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence19.HasEvents());
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(68);
			selector.AddChild(sequence20);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node70 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node70();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49.SetId(70);
			sequence20.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node49.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node71 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node71();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50.SetId(71);
			sequence20.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node50.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node73 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node51 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node73();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node51.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node51.SetId(73);
			sequence20.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node51);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node51.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node72 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node72();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21.SetId(72);
			sequence20.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node21.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence20.HasEvents());
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(74);
			selector.AddChild(sequence21);
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node75 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node52 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node75();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node52.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node52.SetId(75);
			sequence21.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node52);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node52.HasEvents());
			Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node76 condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53 = new Condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node76();
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53.SetId(76);
			sequence21.AddChild(condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node53.HasEvents());
			Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node78 action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22 = new Action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node78();
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22.SetId(78);
			sequence21.AddChild(action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_AutoFight_AutoFight_Gungirl_Manyou_Action_node22.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence21.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
