using System;

namespace behaviac
{
	// Token: 0x02001EF2 RID: 7922
	public static class bt_AutoFight_AutoFight_Fightergirl_Action
	{
		// Token: 0x06012789 RID: 75657 RVA: 0x00567090 File Offset: 0x00565490
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("AutoFight/AutoFight_Fightergirl_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector.AddChild(sequence);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node.SetId(2);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2.SetId(3);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node2.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3.SetId(5);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node3.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4.SetId(4);
			sequence.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node4.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node6 action_bt_AutoFight_AutoFight_Fightergirl_Action_node = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node6();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node.SetId(6);
			sequence.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(31);
			selector.AddChild(sequence2);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node34 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node34();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5.SetId(34);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node5.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node35 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node6 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node35();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node6.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node6.SetId(35);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node6.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node37 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node7 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node37();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node7.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node7.SetId(37);
			sequence2.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node7.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node36 action_bt_AutoFight_AutoFight_Fightergirl_Action_node2 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node36();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node2.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node2.SetId(36);
			sequence2.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(45);
			selector.AddChild(sequence3);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node46 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node46();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8.SetId(46);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node67 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node67();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9.SetId(67);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node53 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node10 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node53();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node10.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node10.SetId(53);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node10.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node54 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node54();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11.SetId(54);
			sequence3.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node55 action_bt_AutoFight_AutoFight_Fightergirl_Action_node3 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node55();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node3.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node3.SetId(55);
			sequence3.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(7);
			selector.AddChild(sequence4);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node12 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node8();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node12.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node12.SetId(8);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node12.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node9();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13.SetId(9);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node11();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14.SetId(11);
			sequence4.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node10 action_bt_AutoFight_AutoFight_Fightergirl_Action_node4 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node10();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node4.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node4.SetId(10);
			sequence4.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(12);
			selector.AddChild(sequence5);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node13();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15.SetId(13);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node16 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node14();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node16.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node16.SetId(14);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node16);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node16.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node17 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node15();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node17.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node17.SetId(15);
			sequence5.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node17);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node17.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node16 action_bt_AutoFight_AutoFight_Fightergirl_Action_node5 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node16();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node5.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node5.SetId(16);
			sequence5.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(17);
			selector.AddChild(sequence6);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18.SetId(18);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node18.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19.SetId(19);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node19.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node32 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node32();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20.SetId(32);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node21 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node20();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node21.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node21.SetId(20);
			sequence6.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node21);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node21.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node21 action_bt_AutoFight_AutoFight_Fightergirl_Action_node6 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node21();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node6.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node6.SetId(21);
			sequence6.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(22);
			selector.AddChild(sequence7);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node22 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node22.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node22.SetId(23);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node22);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node22.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23.SetId(24);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node23.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node33 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node33();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24.SetId(33);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node24.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25.SetId(25);
			sequence7.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node25.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node26 action_bt_AutoFight_AutoFight_Fightergirl_Action_node7 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node26();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node7.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node7.SetId(26);
			sequence7.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(27);
			selector.AddChild(sequence8);
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node28 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node26 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node28();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node26.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node26.SetId(28);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node26);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node26.HasEvents());
			Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node29 condition_bt_AutoFight_AutoFight_Fightergirl_Action_node27 = new Condition_bt_AutoFight_AutoFight_Fightergirl_Action_node29();
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node27.SetClassNameString("Condition");
			condition_bt_AutoFight_AutoFight_Fightergirl_Action_node27.SetId(29);
			sequence8.AddChild(condition_bt_AutoFight_AutoFight_Fightergirl_Action_node27);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_AutoFight_AutoFight_Fightergirl_Action_node27.HasEvents());
			Action_bt_AutoFight_AutoFight_Fightergirl_Action_node30 action_bt_AutoFight_AutoFight_Fightergirl_Action_node8 = new Action_bt_AutoFight_AutoFight_Fightergirl_Action_node30();
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node8.SetClassNameString("Action");
			action_bt_AutoFight_AutoFight_Fightergirl_Action_node8.SetId(30);
			sequence8.AddChild(action_bt_AutoFight_AutoFight_Fightergirl_Action_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_AutoFight_AutoFight_Fightergirl_Action_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
