using System;

namespace behaviac
{
	// Token: 0x02002AA0 RID: 10912
	public static class bt_Guanka_apc_Mofashi_li
	{
		// Token: 0x06013E62 RID: 81506 RVA: 0x005F79D0 File Offset: 0x005F5DD0
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Guanka_apc/Mofashi_li");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector.AddChild(sequence);
			Condition_bt_Guanka_apc_Mofashi_li_node2 condition_bt_Guanka_apc_Mofashi_li_node = new Condition_bt_Guanka_apc_Mofashi_li_node2();
			condition_bt_Guanka_apc_Mofashi_li_node.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node.SetId(2);
			sequence.AddChild(condition_bt_Guanka_apc_Mofashi_li_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node.HasEvents());
			DecoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node15 decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node = new DecoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node15();
			decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node.SetClassNameString("DecoratorAlwaysSuccess");
			decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node.SetId(15);
			sequence.AddChild(decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(3);
			decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node.AddChild(sequence2);
			Condition_bt_Guanka_apc_Mofashi_li_node4 condition_bt_Guanka_apc_Mofashi_li_node2 = new Condition_bt_Guanka_apc_Mofashi_li_node4();
			condition_bt_Guanka_apc_Mofashi_li_node2.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node2.SetId(4);
			sequence2.AddChild(condition_bt_Guanka_apc_Mofashi_li_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(5);
			sequence2.AddChild(sequence3);
			Condition_bt_Guanka_apc_Mofashi_li_node6 condition_bt_Guanka_apc_Mofashi_li_node3 = new Condition_bt_Guanka_apc_Mofashi_li_node6();
			condition_bt_Guanka_apc_Mofashi_li_node3.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node3.SetId(6);
			sequence3.AddChild(condition_bt_Guanka_apc_Mofashi_li_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node3.HasEvents());
			Action_bt_Guanka_apc_Mofashi_li_node7 action_bt_Guanka_apc_Mofashi_li_node = new Action_bt_Guanka_apc_Mofashi_li_node7();
			action_bt_Guanka_apc_Mofashi_li_node.SetClassNameString("Action");
			action_bt_Guanka_apc_Mofashi_li_node.SetId(7);
			sequence3.AddChild(action_bt_Guanka_apc_Mofashi_li_node);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Guanka_apc_Mofashi_li_node.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | sequence3.HasEvents());
			decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node.SetHasEvents(decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node.HasEvents() | sequence2.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | decoratorAlwaysSuccess_bt_Guanka_apc_Mofashi_li_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(8);
			selector.AddChild(sequence4);
			Condition_bt_Guanka_apc_Mofashi_li_node9 condition_bt_Guanka_apc_Mofashi_li_node4 = new Condition_bt_Guanka_apc_Mofashi_li_node9();
			condition_bt_Guanka_apc_Mofashi_li_node4.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node4.SetId(9);
			sequence4.AddChild(condition_bt_Guanka_apc_Mofashi_li_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(10);
			sequence4.AddChild(sequence5);
			Condition_bt_Guanka_apc_Mofashi_li_node11 condition_bt_Guanka_apc_Mofashi_li_node5 = new Condition_bt_Guanka_apc_Mofashi_li_node11();
			condition_bt_Guanka_apc_Mofashi_li_node5.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node5.SetId(11);
			sequence5.AddChild(condition_bt_Guanka_apc_Mofashi_li_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node5.HasEvents());
			Condition_bt_Guanka_apc_Mofashi_li_node14 condition_bt_Guanka_apc_Mofashi_li_node6 = new Condition_bt_Guanka_apc_Mofashi_li_node14();
			condition_bt_Guanka_apc_Mofashi_li_node6.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node6.SetId(14);
			sequence5.AddChild(condition_bt_Guanka_apc_Mofashi_li_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node6.HasEvents());
			Action_bt_Guanka_apc_Mofashi_li_node12 action_bt_Guanka_apc_Mofashi_li_node2 = new Action_bt_Guanka_apc_Mofashi_li_node12();
			action_bt_Guanka_apc_Mofashi_li_node2.SetClassNameString("Action");
			action_bt_Guanka_apc_Mofashi_li_node2.SetId(12);
			sequence5.AddChild(action_bt_Guanka_apc_Mofashi_li_node2);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Guanka_apc_Mofashi_li_node2.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | sequence5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(16);
			selector.AddChild(sequence6);
			Condition_bt_Guanka_apc_Mofashi_li_node17 condition_bt_Guanka_apc_Mofashi_li_node7 = new Condition_bt_Guanka_apc_Mofashi_li_node17();
			condition_bt_Guanka_apc_Mofashi_li_node7.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node7.SetId(17);
			sequence6.AddChild(condition_bt_Guanka_apc_Mofashi_li_node7);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node7.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(18);
			sequence6.AddChild(sequence7);
			Condition_bt_Guanka_apc_Mofashi_li_node19 condition_bt_Guanka_apc_Mofashi_li_node8 = new Condition_bt_Guanka_apc_Mofashi_li_node19();
			condition_bt_Guanka_apc_Mofashi_li_node8.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node8.SetId(19);
			sequence7.AddChild(condition_bt_Guanka_apc_Mofashi_li_node8);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node8.HasEvents());
			Condition_bt_Guanka_apc_Mofashi_li_node20 condition_bt_Guanka_apc_Mofashi_li_node9 = new Condition_bt_Guanka_apc_Mofashi_li_node20();
			condition_bt_Guanka_apc_Mofashi_li_node9.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node9.SetId(20);
			sequence7.AddChild(condition_bt_Guanka_apc_Mofashi_li_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node9.HasEvents());
			Action_bt_Guanka_apc_Mofashi_li_node13 action_bt_Guanka_apc_Mofashi_li_node3 = new Action_bt_Guanka_apc_Mofashi_li_node13();
			action_bt_Guanka_apc_Mofashi_li_node3.SetClassNameString("Action");
			action_bt_Guanka_apc_Mofashi_li_node3.SetId(13);
			sequence7.AddChild(action_bt_Guanka_apc_Mofashi_li_node3);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Guanka_apc_Mofashi_li_node3.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | sequence7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(21);
			selector.AddChild(sequence8);
			Condition_bt_Guanka_apc_Mofashi_li_node22 condition_bt_Guanka_apc_Mofashi_li_node10 = new Condition_bt_Guanka_apc_Mofashi_li_node22();
			condition_bt_Guanka_apc_Mofashi_li_node10.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node10.SetId(22);
			sequence8.AddChild(condition_bt_Guanka_apc_Mofashi_li_node10);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node10.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(23);
			sequence8.AddChild(sequence9);
			Condition_bt_Guanka_apc_Mofashi_li_node24 condition_bt_Guanka_apc_Mofashi_li_node11 = new Condition_bt_Guanka_apc_Mofashi_li_node24();
			condition_bt_Guanka_apc_Mofashi_li_node11.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node11.SetId(24);
			sequence9.AddChild(condition_bt_Guanka_apc_Mofashi_li_node11);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node11.HasEvents());
			Condition_bt_Guanka_apc_Mofashi_li_node25 condition_bt_Guanka_apc_Mofashi_li_node12 = new Condition_bt_Guanka_apc_Mofashi_li_node25();
			condition_bt_Guanka_apc_Mofashi_li_node12.SetClassNameString("Condition");
			condition_bt_Guanka_apc_Mofashi_li_node12.SetId(25);
			sequence9.AddChild(condition_bt_Guanka_apc_Mofashi_li_node12);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Guanka_apc_Mofashi_li_node12.HasEvents());
			Action_bt_Guanka_apc_Mofashi_li_node26 action_bt_Guanka_apc_Mofashi_li_node4 = new Action_bt_Guanka_apc_Mofashi_li_node26();
			action_bt_Guanka_apc_Mofashi_li_node4.SetClassNameString("Action");
			action_bt_Guanka_apc_Mofashi_li_node4.SetId(26);
			sequence9.AddChild(action_bt_Guanka_apc_Mofashi_li_node4);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Guanka_apc_Mofashi_li_node4.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | sequence9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
