using System;

namespace behaviac
{
	// Token: 0x02002B0C RID: 11020
	public static class bt_Level_Tuanben_TuanBen_Wind
	{
		// Token: 0x06013F2C RID: 81708 RVA: 0x005FC97C File Offset: 0x005FAD7C
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Level/Tuanben/TuanBen_Wind");
			bt.IsFSM = false;
			Parallel_bt_Level_Tuanben_TuanBen_Wind_node36 parallel_bt_Level_Tuanben_TuanBen_Wind_node = new Parallel_bt_Level_Tuanben_TuanBen_Wind_node36();
			parallel_bt_Level_Tuanben_TuanBen_Wind_node.SetClassNameString("Parallel");
			parallel_bt_Level_Tuanben_TuanBen_Wind_node.SetId(36);
			bt.AddChild(parallel_bt_Level_Tuanben_TuanBen_Wind_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(37);
			parallel_bt_Level_Tuanben_TuanBen_Wind_node.AddChild(sequence);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node38 condition_bt_Level_Tuanben_TuanBen_Wind_node = new Condition_bt_Level_Tuanben_TuanBen_Wind_node38();
			condition_bt_Level_Tuanben_TuanBen_Wind_node.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node.SetId(38);
			sequence.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node39 condition_bt_Level_Tuanben_TuanBen_Wind_node2 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node39();
			condition_bt_Level_Tuanben_TuanBen_Wind_node2.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node2.SetId(39);
			sequence.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node2.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node40 action_bt_Level_Tuanben_TuanBen_Wind_node = new Action_bt_Level_Tuanben_TuanBen_Wind_node40();
			action_bt_Level_Tuanben_TuanBen_Wind_node.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node.SetId(40);
			sequence.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node.HasEvents());
			Assignment_bt_Level_Tuanben_TuanBen_Wind_node41 assignment_bt_Level_Tuanben_TuanBen_Wind_node = new Assignment_bt_Level_Tuanben_TuanBen_Wind_node41();
			assignment_bt_Level_Tuanben_TuanBen_Wind_node.SetClassNameString("Assignment");
			assignment_bt_Level_Tuanben_TuanBen_Wind_node.SetId(41);
			sequence.AddChild(assignment_bt_Level_Tuanben_TuanBen_Wind_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_Level_Tuanben_TuanBen_Wind_node.HasEvents());
			parallel_bt_Level_Tuanben_TuanBen_Wind_node.SetHasEvents(parallel_bt_Level_Tuanben_TuanBen_Wind_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(1);
			parallel_bt_Level_Tuanben_TuanBen_Wind_node.AddChild(sequence2);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(34);
			sequence2.AddChild(sequence3);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node5 condition_bt_Level_Tuanben_TuanBen_Wind_node3 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node5();
			condition_bt_Level_Tuanben_TuanBen_Wind_node3.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node3.SetId(5);
			sequence3.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node3.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node35 action_bt_Level_Tuanben_TuanBen_Wind_node2 = new Action_bt_Level_Tuanben_TuanBen_Wind_node35();
			action_bt_Level_Tuanben_TuanBen_Wind_node2.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node2.SetId(35);
			sequence3.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node2.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node4 action_bt_Level_Tuanben_TuanBen_Wind_node3 = new Action_bt_Level_Tuanben_TuanBen_Wind_node4();
			action_bt_Level_Tuanben_TuanBen_Wind_node3.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node3.SetId(4);
			sequence3.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(42);
			sequence3.AddChild(sequence4);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(15);
			sequence4.AddChild(selector);
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(2);
			selector.AddChild(sequence5);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node6 condition_bt_Level_Tuanben_TuanBen_Wind_node4 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node6();
			condition_bt_Level_Tuanben_TuanBen_Wind_node4.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node4.SetId(6);
			sequence5.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node4.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node8 action_bt_Level_Tuanben_TuanBen_Wind_node4 = new Action_bt_Level_Tuanben_TuanBen_Wind_node8();
			action_bt_Level_Tuanben_TuanBen_Wind_node4.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node4.SetId(8);
			sequence5.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(9);
			selector.AddChild(sequence6);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node10 condition_bt_Level_Tuanben_TuanBen_Wind_node5 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node10();
			condition_bt_Level_Tuanben_TuanBen_Wind_node5.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node5.SetId(10);
			sequence6.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node5.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node0 action_bt_Level_Tuanben_TuanBen_Wind_node5 = new Action_bt_Level_Tuanben_TuanBen_Wind_node0();
			action_bt_Level_Tuanben_TuanBen_Wind_node5.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node5.SetId(0);
			sequence6.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(3);
			selector.AddChild(sequence7);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node12 condition_bt_Level_Tuanben_TuanBen_Wind_node6 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node12();
			condition_bt_Level_Tuanben_TuanBen_Wind_node6.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node6.SetId(12);
			sequence7.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node6.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node13 action_bt_Level_Tuanben_TuanBen_Wind_node6 = new Action_bt_Level_Tuanben_TuanBen_Wind_node13();
			action_bt_Level_Tuanben_TuanBen_Wind_node6.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node6.SetId(13);
			sequence7.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | selector.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | sequence4.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | sequence3.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(7);
			sequence2.AddChild(sequence8);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node11 condition_bt_Level_Tuanben_TuanBen_Wind_node7 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node11();
			condition_bt_Level_Tuanben_TuanBen_Wind_node7.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node7.SetId(11);
			sequence8.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node7);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node7.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node22 condition_bt_Level_Tuanben_TuanBen_Wind_node8 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node22();
			condition_bt_Level_Tuanben_TuanBen_Wind_node8.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node8.SetId(22);
			sequence8.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node8.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node23 condition_bt_Level_Tuanben_TuanBen_Wind_node9 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node23();
			condition_bt_Level_Tuanben_TuanBen_Wind_node9.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node9.SetId(23);
			sequence8.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node9);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node9.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(17);
			sequence8.AddChild(selector2);
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(18);
			selector2.AddChild(sequence9);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node24 condition_bt_Level_Tuanben_TuanBen_Wind_node10 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node24();
			condition_bt_Level_Tuanben_TuanBen_Wind_node10.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node10.SetId(24);
			sequence9.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node10);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node10.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node20 condition_bt_Level_Tuanben_TuanBen_Wind_node11 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node20();
			condition_bt_Level_Tuanben_TuanBen_Wind_node11.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node11.SetId(20);
			sequence9.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node11);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node11.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node14 action_bt_Level_Tuanben_TuanBen_Wind_node7 = new Action_bt_Level_Tuanben_TuanBen_Wind_node14();
			action_bt_Level_Tuanben_TuanBen_Wind_node7.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node7.SetId(14);
			sequence9.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node7);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node7.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(19);
			selector2.AddChild(sequence10);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node25 condition_bt_Level_Tuanben_TuanBen_Wind_node12 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node25();
			condition_bt_Level_Tuanben_TuanBen_Wind_node12.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node12.SetId(25);
			sequence10.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node12);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node12.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node21 condition_bt_Level_Tuanben_TuanBen_Wind_node13 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node21();
			condition_bt_Level_Tuanben_TuanBen_Wind_node13.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node13.SetId(21);
			sequence10.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node13);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node13.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node16 action_bt_Level_Tuanben_TuanBen_Wind_node8 = new Action_bt_Level_Tuanben_TuanBen_Wind_node16();
			action_bt_Level_Tuanben_TuanBen_Wind_node8.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node8.SetId(16);
			sequence10.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node8);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node8.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(26);
			selector2.AddChild(sequence11);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node27 condition_bt_Level_Tuanben_TuanBen_Wind_node14 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node27();
			condition_bt_Level_Tuanben_TuanBen_Wind_node14.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node14.SetId(27);
			sequence11.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node14);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node14.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node28 condition_bt_Level_Tuanben_TuanBen_Wind_node15 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node28();
			condition_bt_Level_Tuanben_TuanBen_Wind_node15.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node15.SetId(28);
			sequence11.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node15);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node15.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node30 action_bt_Level_Tuanben_TuanBen_Wind_node9 = new Action_bt_Level_Tuanben_TuanBen_Wind_node30();
			action_bt_Level_Tuanben_TuanBen_Wind_node9.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node9.SetId(30);
			sequence11.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node9);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node9.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(29);
			selector2.AddChild(sequence12);
			Condition_bt_Level_Tuanben_TuanBen_Wind_node31 condition_bt_Level_Tuanben_TuanBen_Wind_node16 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node31();
			condition_bt_Level_Tuanben_TuanBen_Wind_node16.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node16.SetId(31);
			sequence12.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node16);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node16.HasEvents());
			Condition_bt_Level_Tuanben_TuanBen_Wind_node32 condition_bt_Level_Tuanben_TuanBen_Wind_node17 = new Condition_bt_Level_Tuanben_TuanBen_Wind_node32();
			condition_bt_Level_Tuanben_TuanBen_Wind_node17.SetClassNameString("Condition");
			condition_bt_Level_Tuanben_TuanBen_Wind_node17.SetId(32);
			sequence12.AddChild(condition_bt_Level_Tuanben_TuanBen_Wind_node17);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Level_Tuanben_TuanBen_Wind_node17.HasEvents());
			Action_bt_Level_Tuanben_TuanBen_Wind_node33 action_bt_Level_Tuanben_TuanBen_Wind_node10 = new Action_bt_Level_Tuanben_TuanBen_Wind_node33();
			action_bt_Level_Tuanben_TuanBen_Wind_node10.SetClassNameString("Action");
			action_bt_Level_Tuanben_TuanBen_Wind_node10.SetId(33);
			sequence12.AddChild(action_bt_Level_Tuanben_TuanBen_Wind_node10);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Level_Tuanben_TuanBen_Wind_node10.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
			sequence8.SetHasEvents(sequence8.HasEvents() | selector2.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | sequence8.HasEvents());
			parallel_bt_Level_Tuanben_TuanBen_Wind_node.SetHasEvents(parallel_bt_Level_Tuanben_TuanBen_Wind_node.HasEvents() | sequence2.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Level_Tuanben_TuanBen_Wind_node.HasEvents());
			return true;
		}
	}
}
