using System;

namespace behaviac
{
	// Token: 0x02002F03 RID: 12035
	public static class bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT
	{
		// Token: 0x060146DE RID: 83678 RVA: 0x00624F84 File Offset: 0x00623384
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/Fengkuangdexide_Boss_EVENT");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node0 parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node = new Parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node0();
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetId(0);
			bt.AddChild(parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(18);
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node52 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node52();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetId(52);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node19 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node19();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetId(19);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node20 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node20();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.SetId(20);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node53 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node53();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3.SetId(53);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(21);
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node22 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node22();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.SetId(22);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node23 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node23();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4.SetId(23);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node24 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node24();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5.SetId(24);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(1);
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node49 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node49();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3.SetId(49);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node12 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node12();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4.SetId(12);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node4.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node28 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node28();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5.SetId(28);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node15 assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node = new Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node15();
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetId(15);
			sequence3.AddChild(assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6.SetId(2);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node3();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7.SetId(3);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(4);
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node25 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node25();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6.SetId(25);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node13 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node13();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7.SetId(13);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node5();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8.SetId(5);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node16 assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2 = new Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node16();
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.SetId(16);
			sequence4.AddChild(assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node6();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8.SetId(6);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node8.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node9 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node7();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node9.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node9.SetId(7);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node9.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents() | sequence4.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_EVENT_node.HasEvents());
			return true;
		}
	}
}
