using System;

namespace behaviac
{
	// Token: 0x02003B3C RID: 15164
	public static class bt_Monster_AI_Tuanben_Shuiren_Boss
	{
		// Token: 0x06015E30 RID: 89648 RVA: 0x0069C8A4 File Offset: 0x0069ACA4
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben/Shuiren_Boss");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(4);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node30 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node30();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node.SetId(30);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.SetId(5);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node.SetId(6);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node31 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node31();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node.SetId(31);
			sequence.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(7);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node32 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node3 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node32();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.SetId(32);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node4 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.SetId(8);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node2 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.SetId(9);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node39 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node2 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node39();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.SetId(39);
			sequence2.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(10);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node33 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node33();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.SetId(33);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node6 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.SetId(11);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node12 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node12();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.SetId(12);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node40 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node3 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node40();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.SetId(40);
			sequence3.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(13);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node34 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node7 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node34();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.SetId(34);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.SetId(14);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node15 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node4 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node15();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.SetId(15);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node41 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node4 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node41();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.SetId(41);
			sequence4.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(16);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node35 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node9 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node35();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.SetId(35);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node10 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node10.SetId(17);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node10.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node18 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node5 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node18();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.SetId(18);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node42 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node5 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node42();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.SetId(42);
			sequence5.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(19);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node36 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node36();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11.SetId(36);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node11.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node20 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node12 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node20();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node12.SetId(20);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node12);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node12.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node21 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node21();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.SetId(21);
			sequence6.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node43 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node6 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node43();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.SetId(43);
			sequence6.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(28);
			selector.AddChild(sequence7);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node38 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node13 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node38();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node13.SetId(38);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node13.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node26 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node26();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14.SetId(26);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node14.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node27 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node7 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node27();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.SetId(27);
			sequence7.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node45 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node7 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node45();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.SetId(45);
			sequence7.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(22);
			selector.AddChild(sequence8);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node37 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node15 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node37();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node15.SetId(37);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node15.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node23 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node16 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node23();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node16.SetId(23);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node16);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node16.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node24 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node8 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node24();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.SetId(24);
			sequence8.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node44 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node8 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node44();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.SetId(44);
			sequence8.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(1);
			selector.AddChild(sequence9);
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node25 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node25();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17.SetId(25);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node17.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2 condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node18 = new Condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node2();
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node18.SetId(2);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node18);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_Shuiren_Boss_node18.HasEvents());
			Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3 action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9 = new Action_bt_Monster_AI_Tuanben_Shuiren_Boss_node3();
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.SetId(3);
			sequence9.AddChild(action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node29 assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node9 = new Assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node29();
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.SetId(29);
			sequence9.AddChild(assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | assignment_bt_Monster_AI_Tuanben_Shuiren_Boss_node9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
