using System;

namespace behaviac
{
	// Token: 0x02004066 RID: 16486
	public static class bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action
	{
		// Token: 0x0601682B RID: 92203 RVA: 0x006CFCE4 File Offset: 0x006CE0E4
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/zhaohuanshi1/zhaohuanshi_Gebulin_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(1);
			selector.AddChild(selector2);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(4);
			selector2.AddChild(sequence);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node.SetId(5);
			sequence.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2.SetId(6);
			sequence.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3.SetId(7);
			sequence.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node.SetId(8);
			sequence.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(9);
			selector2.AddChild(sequence2);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4.SetId(10);
			sequence2.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5.SetId(11);
			sequence2.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6.SetId(12);
			sequence2.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2.SetId(13);
			sequence2.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node2.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(14);
			selector2.AddChild(sequence3);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7.SetId(15);
			sequence3.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8.SetId(16);
			sequence3.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9.SetId(17);
			sequence3.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3.SetId(18);
			sequence3.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node3.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(19);
			selector2.AddChild(sequence4);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10.SetId(20);
			sequence4.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11.SetId(21);
			sequence4.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12.SetId(22);
			sequence4.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4.SetId(23);
			sequence4.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node4.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(24);
			selector2.AddChild(sequence5);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13.SetId(25);
			sequence5.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node13.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node14 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node14.SetId(26);
			sequence5.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node14.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15.SetId(27);
			sequence5.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node15.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5.SetId(28);
			sequence5.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node5.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector2.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(2);
			selector.AddChild(selector3);
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(29);
			selector3.AddChild(sequence6);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16.SetId(30);
			sequence6.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node16.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17.SetId(31);
			sequence6.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node17.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18.SetId(32);
			sequence6.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node18.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6.SetId(33);
			sequence6.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node6.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(34);
			selector3.AddChild(sequence7);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node19 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node19.SetId(35);
			sequence7.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node19.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20.SetId(36);
			sequence7.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node20.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node37 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node37();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21.SetId(37);
			sequence7.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node21.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node38 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node38();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7.SetId(38);
			sequence7.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node7.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(39);
			selector3.AddChild(sequence8);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node40 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node40();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22.SetId(40);
			sequence8.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node22.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node41 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node41();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23.SetId(41);
			sequence8.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node23.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node42 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node24 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node42();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node24.SetId(42);
			sequence8.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node24);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node24.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node43 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node43();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8.SetId(43);
			sequence8.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node8.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(44);
			selector3.AddChild(sequence9);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node45 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node45();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25.SetId(45);
			sequence9.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node25.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node46 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node46();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26.SetId(46);
			sequence9.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node26.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node47 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node47();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27.SetId(47);
			sequence9.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node27.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node48 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node48();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9.SetId(48);
			sequence9.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node9.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(49);
			selector3.AddChild(sequence10);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node50 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node50();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28.SetId(50);
			sequence10.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node28.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node51 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node29 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node51();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node29.SetId(51);
			sequence10.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node29);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node29.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node52 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node52();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30.SetId(52);
			sequence10.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node30.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node53 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node53();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10.SetId(53);
			sequence10.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node10.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence10.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector3.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(3);
			selector.AddChild(selector4);
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(54);
			selector4.AddChild(sequence11);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node55 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node55();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31.SetId(55);
			sequence11.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node31.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node56 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node56();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32.SetId(56);
			sequence11.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node32.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node57 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node57();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33.SetId(57);
			sequence11.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node33.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node58 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node58();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11.SetId(58);
			sequence11.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node11.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(59);
			selector4.AddChild(sequence12);
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node60 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node34 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node60();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node34.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node34.SetId(60);
			sequence12.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node34);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node34.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node61 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node61();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35.SetId(61);
			sequence12.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node35.HasEvents());
			Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node62 condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36 = new Condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node62();
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36.SetClassNameString("Condition");
			condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36.SetId(62);
			sequence12.AddChild(condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node36.HasEvents());
			Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node63 action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12 = new Action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node63();
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12.SetClassNameString("Action");
			action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12.SetId(63);
			sequence12.AddChild(action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_zhaohuanshi1_zhaohuanshi_Gebulin_Action_node12.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence12.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector4.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
