using System;

namespace behaviac
{
	// Token: 0x02003309 RID: 13065
	public static class bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination
	{
		// Token: 0x06014E7C RID: 85628 RVA: 0x0064C4F0 File Offset: 0x0064A8F0
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/GoblinKingdom/Goblin_danxiao_Destination");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(18);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(2);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node19 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node19();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node.SetId(19);
			sequence.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node20 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node20();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2.SetId(20);
			sequence.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node21 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node21();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node.SetId(21);
			sequence.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(0);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3.SetId(6);
			sequence2.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4.SetId(5);
			sequence2.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node23 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node23();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2.SetId(23);
			sequence2.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node2.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3.SetId(4);
			sequence2.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(3);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5.SetId(8);
			sequence3.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6.SetId(7);
			sequence3.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4.SetId(9);
			sequence3.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(11);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node16 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node16();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7.SetId(16);
			sequence4.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node12 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node12();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8.SetId(12);
			sequence4.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node22 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node22();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5.SetId(22);
			sequence4.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node5.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6.SetId(10);
			sequence4.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(13);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node17 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node17();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9.SetId(17);
			sequence5.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node9.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node14 condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10 = new Condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node14();
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10.SetId(14);
			sequence5.AddChild(condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node10.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node15 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node15();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7.SetId(15);
			sequence5.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node1 action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8 = new Action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node1();
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8.SetId(1);
			selector.AddChild(action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8);
			selector.SetHasEvents(selector.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Goblin_danxiao_Destination_node8.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
