using System;

namespace behaviac
{
	// Token: 0x02003EE1 RID: 16097
	public static class bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect
	{
		// Token: 0x0601653E RID: 91454 RVA: 0x006C0E04 File Offset: 0x006BF204
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Zhanguo/Boss_zhentianxincun_DestinationSelect");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(1);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(2);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node.SetId(5);
			sequence.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node.HasEvents());
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node0 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node0();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2.SetId(0);
			sequence.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2.HasEvents());
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3.SetId(4);
			sequence.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3.HasEvents());
			Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6 action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node = new Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6();
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node.SetClassNameString("Action");
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node.SetId(6);
			sequence.AddChild(action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(10);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4.SetId(11);
			sequence2.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4.HasEvents());
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node14 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node14();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5.SetId(14);
			sequence2.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(20);
			sequence2.AddChild(selector2);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(23);
			selector2.AddChild(sequence3);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node24 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node24();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6.SetId(24);
			sequence3.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6.HasEvents());
			Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node25 action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2 = new Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node25();
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2.SetId(25);
			sequence3.AddChild(action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node2.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(3);
			selector2.AddChild(sequence4);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7.SetId(7);
			sequence4.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node7.HasEvents());
			Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8 action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3 = new Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8();
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3.SetId(8);
			sequence4.AddChild(action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node3.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(22);
			selector2.AddChild(sequence5);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node12 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node12();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8.SetId(12);
			sequence5.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node8.HasEvents());
			Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node13 action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4 = new Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node13();
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4.SetId(13);
			sequence5.AddChild(action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node4.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence5.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | selector2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(17);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node18 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node9 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node18();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node9.SetId(18);
			sequence6.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node9.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(21);
			sequence6.AddChild(selector3);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(19);
			selector3.AddChild(sequence7);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node26 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node10 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node26();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node10.SetId(26);
			sequence7.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node10);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node10.HasEvents());
			Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node30 action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5 = new Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node30();
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5.SetId(30);
			sequence7.AddChild(action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node5.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(9);
			selector3.AddChild(sequence8);
			Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node15 condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11 = new Condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node15();
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11.SetId(15);
			sequence8.AddChild(condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node11.HasEvents());
			Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node27 action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6 = new Action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node27();
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6.SetId(27);
			sequence8.AddChild(action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Zhanguo_Boss_zhentianxincun_DestinationSelect_node6.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence8.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selector3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
