using System;

namespace behaviac
{
	// Token: 0x0200399D RID: 14749
	public static class bt_Monster_AI_Tuanben_Eyujingyin_Event
	{
		// Token: 0x06015B0F RID: 88847 RVA: 0x0068D068 File Offset: 0x0068B468
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben/Eyujingyin_Event");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3 parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node = new Parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3();
			parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetId(3);
			bt.AddChild(parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(18);
			parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetId(5);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node1 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2 = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node1();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2.SetId(1);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetId(2);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node11 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node11();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2.SetId(11);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node14 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node14();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3.SetId(14);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(4);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3 = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3.SetId(6);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node3.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4 = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4.SetId(7);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4.SetId(8);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5.SetId(9);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6.SetId(10);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.HasEvents() | selector.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(17);
			parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node12 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5 = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node12();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5.SetId(12);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node5.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(19);
			sequence3.AddChild(selector2);
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(20);
			selector2.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node21 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6 = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node21();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6.SetId(21);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node6.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node13 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node13();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7.SetId(13);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node22 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node22();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8.SetId(22);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node8.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(23);
			selector2.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node24 condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7 = new Condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node24();
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7.SetId(24);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Eyujingyin_Event_node7.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node25 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node25();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9.SetId(25);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node9.HasEvents());
			Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node26 action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10 = new Action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node26();
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10.SetId(26);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_Eyujingyin_Event_node10.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence5.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | selector2.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.HasEvents() | sequence3.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Tuanben_Eyujingyin_Event_node.HasEvents());
			return true;
		}
	}
}
