using System;

namespace behaviac
{
	// Token: 0x0200341A RID: 13338
	public static class bt_Monster_AI_Heisedadi_Huimie_Action
	{
		// Token: 0x06015085 RID: 86149 RVA: 0x00656008 File Offset: 0x00654408
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Heisedadi/Huimie_Action");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(7);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(16);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node17 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node17();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node.SetId(17);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node18 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node2 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node18();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node2.SetId(18);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node2.HasEvents());
			Assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node42 assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node = new Assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node42();
			assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node.SetId(42);
			sequence.AddChild(assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_Monster_AI_Heisedadi_Huimie_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(44);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3.SetId(6);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node45 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node45();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4.SetId(45);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node46 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node46();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5.SetId(46);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node3();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6.SetId(3);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node6.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Action_node0 action_bt_Monster_AI_Heisedadi_Huimie_Action_node = new Action_bt_Monster_AI_Heisedadi_Huimie_Action_node0();
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node.SetId(0);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Action_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(39);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node7 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node7.SetId(9);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node7.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node40 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node8 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node40();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node8.SetId(40);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node8.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node41 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node41();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9.SetId(41);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node9.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Action_node1 action_bt_Monster_AI_Heisedadi_Huimie_Action_node2 = new Action_bt_Monster_AI_Heisedadi_Huimie_Action_node1();
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node2.SetId(1);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Action_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(8);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10.SetId(10);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node10.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node11 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node5();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node11.SetId(5);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node11.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node31 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node31();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12.SetId(31);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node4();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13.SetId(4);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Action_node11 action_bt_Monster_AI_Heisedadi_Huimie_Action_node3 = new Action_bt_Monster_AI_Heisedadi_Huimie_Action_node11();
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node3.SetId(11);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Action_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(2);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node12();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14.SetId(12);
			sequence5.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node15 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node13();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node15.SetId(13);
			sequence5.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node15.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14 condition_bt_Monster_AI_Heisedadi_Huimie_Action_node16 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Action_node14();
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Action_node16.SetId(14);
			sequence5.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Action_node16);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Action_node16.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Action_node15 action_bt_Monster_AI_Heisedadi_Huimie_Action_node4 = new Action_bt_Monster_AI_Heisedadi_Huimie_Action_node15();
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Action_node4.SetId(15);
			sequence5.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Action_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
