using System;

namespace behaviac
{
	// Token: 0x02002B7E RID: 11134
	public static class bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION
	{
		// Token: 0x06014009 RID: 81929 RVA: 0x006016AC File Offset: 0x005FFAAC
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/65TB_Chuanyuezhe_DESTINATION");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(2);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node9 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node9();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetId(9);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node1 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node1();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetId(1);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node21 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node21();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetId(21);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(3);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node11 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node11();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3.SetId(11);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4.SetId(4);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node10 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node10();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5.SetId(10);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetId(5);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(6);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node12 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node12();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6.SetId(12);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7.SetId(7);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node7.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3.SetId(8);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(17);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node18 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node18();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8.SetId(18);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node8.HasEvents());
			SelectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node19 selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node = new SelectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node19();
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetClassNameString("SelectorProbability");
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetId(19);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.Initialize("Self.BTAgent::Action_GenRandom()");
			sequence4.AddChild(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node);
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node20 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node20();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetId(20);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node);
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(22);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.AddChild(sequence5);
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node23 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node23();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4.SetId(23);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node4.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents() | sequence5.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents());
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node24 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2 = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node24();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetId(24);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2);
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(13);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.AddChild(sequence6);
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node14 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node14();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5.SetId(14);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node5.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node15 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node15();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6.SetId(15);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node6.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.HasEvents() | sequence6.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node2.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_DESTINATION_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
