using System;

namespace behaviac
{
	// Token: 0x02003CAF RID: 15535
	public static class bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard
	{
		// Token: 0x06016105 RID: 90373 RVA: 0x006AA6D0 File Offset: 0x006A8AD0
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben_hard/KexilaXianshi_Boss_ACTION_hard");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(3);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(80);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node83 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node83();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node.SetId(83);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node85 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node85();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2.SetId(85);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node97 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node97();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3.SetId(97);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node98 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node98();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4.SetId(98);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node99 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node99();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5.SetId(99);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node84 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node84();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6.SetId(84);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node82 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node82();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7.SetId(82);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node81 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node81();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node.SetId(81);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2.SetId(8);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(6);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node77 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node77();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8.SetId(77);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node54 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node54();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9.SetId(54);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10.SetId(15);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3.SetId(12);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(78);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node2();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11.SetId(2);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node76 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node76();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12.SetId(76);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node72 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node72();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13.SetId(72);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node90 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node90();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14.SetId(90);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node91 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node91();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15.SetId(91);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node95 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node95();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16.SetId(95);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node58 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node58();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17.SetId(58);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node57 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node18 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node57();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node18.SetId(57);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node18);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node18.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node75 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node75();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4.SetId(75);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node92 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node92();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5.SetId(92);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(1);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node79 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node79();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19.SetId(79);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(0);
			sequence4.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node5();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20.SetId(5);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node4();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21.SetId(4);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6.SetId(7);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node6.HasEvents());
			sequence4.SetHasEvents(sequence4.HasEvents() | sequence5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(13);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node22 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node22.SetId(14);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node22);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node22.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(55);
			sequence6.AddChild(selector2);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(17);
			selector2.AddChild(sequence7);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23.SetId(39);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24.SetId(45);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7.SetId(16);
			sequence7.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node7.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(18);
			selector2.AddChild(sequence8);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node25 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node19();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node25.SetId(19);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node25);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node25.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26.SetId(46);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node20();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8.SetId(20);
			sequence8.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node8.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence8.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selector2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(11);
			selector.AddChild(sequence9);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node21();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27.SetId(21);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(10);
			sequence9.AddChild(selector3);
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(22);
			selector3.AddChild(sequence10);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node28 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node23();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node28.SetId(23);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node28);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node28.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29.SetId(50);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node24();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9.SetId(24);
			sequence10.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node9.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(25);
			selector3.AddChild(sequence11);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node30 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node26();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node30.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node30.SetId(26);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node30);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node30.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31.SetId(47);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node27();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10.SetId(27);
			sequence11.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node10.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence11.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selector3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(28);
			selector.AddChild(sequence12);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node29();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32.SetId(29);
			sequence12.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(53);
			sequence12.AddChild(selector4);
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(30);
			selector4.AddChild(sequence13);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node33 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node31();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node33.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node33.SetId(31);
			sequence13.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node33);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node33.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34.SetId(51);
			sequence13.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node32();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11.SetId(32);
			sequence13.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node11.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence13.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(33);
			selector4.AddChild(sequence14);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node34();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35.SetId(34);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node36 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node36.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node36.SetId(48);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node36);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node36.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node35();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12.SetId(35);
			sequence14.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node12.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence14.HasEvents());
			sequence12.SetHasEvents(sequence12.HasEvents() | selector4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(36);
			selector.AddChild(sequence15);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37.SetId(37);
			sequence15.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node37.HasEvents());
			Selector selector5 = new Selector();
			selector5.SetClassNameString("Selector");
			selector5.SetId(9);
			sequence15.AddChild(selector5);
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(38);
			selector5.AddChild(sequence16);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node38 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node38.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node38.SetId(40);
			sequence16.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node38);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node38.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39.SetId(52);
			sequence16.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node39.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13.SetId(41);
			sequence16.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node13.HasEvents());
			selector5.SetHasEvents(selector5.HasEvents() | sequence16.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(42);
			selector5.AddChild(sequence17);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40.SetId(43);
			sequence17.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node40.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41.SetId(49);
			sequence17.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node41.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14.SetId(44);
			sequence17.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node14.HasEvents());
			selector5.SetHasEvents(selector5.HasEvents() | sequence17.HasEvents());
			sequence15.SetHasEvents(sequence15.HasEvents() | selector5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence15.HasEvents());
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(62);
			selector.AddChild(sequence18);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node73 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node42 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node73();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node42.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node42.SetId(73);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node42);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node42.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node87 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node87();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43.SetId(87);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node43.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node88 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node88();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44.SetId(88);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node44.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node89 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node89();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45.SetId(89);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node45.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node74 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node74();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46.SetId(74);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node46.HasEvents());
			Selector selector6 = new Selector();
			selector6.SetClassNameString("Selector");
			selector6.SetId(86);
			sequence18.AddChild(selector6);
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(63);
			selector6.AddChild(sequence19);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node64 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node64();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47.SetId(64);
			sequence19.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node47.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node65 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node65();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48.SetId(65);
			sequence19.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node48.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node66 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node66();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15.SetId(66);
			sequence19.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15);
			sequence19.SetHasEvents(sequence19.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node15.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence19.HasEvents());
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(67);
			selector6.AddChild(sequence20);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node68 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node68();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49.SetId(68);
			sequence20.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node49.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node71 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node71();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50.SetId(71);
			sequence20.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node50.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node69 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node69();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51.SetId(69);
			sequence20.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node51.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node70 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node70();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16.SetId(70);
			sequence20.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node16.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence20.HasEvents());
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(56);
			selector6.AddChild(sequence21);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node59 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node59();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52.SetId(59);
			sequence21.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node52.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node60 condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node53 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node60();
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node53.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node53.SetId(60);
			sequence21.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node53);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node53.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node61 action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17 = new Action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node61();
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17.SetId(61);
			sequence21.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaXianshi_Boss_ACTION_hard_node17.HasEvents());
			selector6.SetHasEvents(selector6.HasEvents() | sequence21.HasEvents());
			sequence18.SetHasEvents(sequence18.HasEvents() | selector6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence18.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
