using System;

namespace behaviac
{
	// Token: 0x02002EEE RID: 12014
	public static class bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION
	{
		// Token: 0x060146B6 RID: 83638 RVA: 0x0062365C File Offset: 0x00621A5C
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/Fengkuangdexide_Boss_ACTION");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(15);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node58 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node58();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetId(58);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetId(16);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetId(18);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(27);
			selector.AddChild(selector2);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(7);
			selector2.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node79 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node79();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3.SetId(79);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4.SetId(36);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5.SetId(28);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6.SetId(29);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7.SetId(8);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetId(9);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38 assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node = new Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38();
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetId(38);
			sequence2.AddChild(assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(30);
			selector2.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node83 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node83();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8.SetId(83);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9.SetId(37);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10.SetId(32);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11.SetId(33);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12.SetId(34);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3.SetId(35);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39 assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2 = new Assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39();
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetId(39);
			sequence3.AddChild(assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector2.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(46);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node57 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node57();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13.SetId(57);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node55 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node55();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14.SetId(55);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node48 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node48();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15.SetId(48);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node56 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node56();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16.SetId(56);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node16.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node84 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node84();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17.SetId(84);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node53 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node53();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4.SetId(53);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(54);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node52 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node52();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18.SetId(52);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node18.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(45);
			sequence5.AddChild(selector3);
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(59);
			selector3.AddChild(sequence6);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node49 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node19 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node49();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node19.SetId(49);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node19);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node19.HasEvents());
			SelectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42 selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node = new SelectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42();
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetClassNameString("SelectorProbability");
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetId(42);
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.Initialize("Self.BTAgent::Action_GenRandom()");
			sequence6.AddChild(selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node);
			DecoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41 decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node = new DecoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41();
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetId(41);
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(21);
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.AddChild(sequence7);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20.SetId(22);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5.SetId(24);
			sequence7.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node50 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node50();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6.SetId(50);
			sequence7.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents() | sequence7.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents());
			DecoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43 decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2 = new DecoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43();
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetId(43);
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2);
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(10);
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.AddChild(sequence8);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node21 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node21.SetId(11);
			sequence8.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node21);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node21.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7.SetId(12);
			sequence8.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node7.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node51 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node51();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8.SetId(51);
			sequence8.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node8.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.HasEvents() | sequence8.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selectorProbability_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence6.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(19);
			selector3.AddChild(sequence9);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node47 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node47();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22.SetId(47);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node22.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node20();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23.SetId(20);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node23();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24.SetId(23);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node24.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9.SetId(31);
			sequence9.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node9.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence9.HasEvents());
			sequence5.SetHasEvents(sequence5.HasEvents() | selector3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(64);
			selector.AddChild(sequence10);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node62 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node62();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25.SetId(62);
			sequence10.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node85 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node85();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26.SetId(85);
			sequence10.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(63);
			sequence10.AddChild(selector4);
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(13);
			selector4.AddChild(sequence11);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node65 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node27 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node65();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node27.SetId(65);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node27);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node27.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node66 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node66();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28.SetId(66);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node28.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29.SetId(44);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node29.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node30 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node30.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node30.SetId(14);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node30);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node30.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node17();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10.SetId(17);
			sequence11.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node10.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(68);
			selector4.AddChild(sequence12);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node69 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node69();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31.SetId(69);
			sequence12.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node31.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node70 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node70();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32.SetId(70);
			sequence12.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node32.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node71 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node71();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33.SetId(71);
			sequence12.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node33.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node72 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node72();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34.SetId(72);
			sequence12.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node34.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node73 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node73();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11.SetId(73);
			sequence12.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node11.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence12.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(74);
			selector4.AddChild(sequence13);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node75 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node75();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35.SetId(75);
			sequence13.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node35.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node77 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node77();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36.SetId(77);
			sequence13.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node36.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node78 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node78();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37.SetId(78);
			sequence13.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node37.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node67 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node67();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12.SetId(67);
			sequence13.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node12.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence13.HasEvents());
			sequence10.SetHasEvents(sequence10.HasEvents() | selector4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(4);
			selector.AddChild(sequence14);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node61 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node61();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38.SetId(61);
			sequence14.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node38.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node26();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39.SetId(26);
			sequence14.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node39.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node5();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40.SetId(5);
			sequence14.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node6();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13.SetId(6);
			sequence14.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node13.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(76);
			selector.AddChild(sequence15);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node40();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41.SetId(40);
			sequence15.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node41.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node80 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node80();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42.SetId(80);
			sequence15.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node42.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node81 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node81();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43.SetId(81);
			sequence15.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node43.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node82 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node82();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14.SetId(82);
			sequence15.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node14.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(1);
			selector.AddChild(sequence16);
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node60 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node60();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44.SetId(60);
			sequence16.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node44.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node45 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node25();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node45.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node45.SetId(25);
			sequence16.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node45);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node45.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2 condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node46 = new Condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node2();
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node46.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node46.SetId(2);
			sequence16.AddChild(condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node46);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node46.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3 action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15 = new Action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node3();
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15.SetId(3);
			sequence16.AddChild(action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_Monster_AI_65Tuanben_Fengkuangdexide_Boss_ACTION_node15.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence16.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
