using System;

namespace behaviac
{
	// Token: 0x02002D86 RID: 11654
	public static class bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION
	{
		// Token: 0x060143EE RID: 82926 RVA: 0x00614B64 File Offset: 0x00612F64
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/Dajisi_Boss_ACTION");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(16);
			bt.AddChild(selector);
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(0);
			selector.AddChild(selector2);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			selector2.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node28 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node28();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node.SetId(28);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2.SetId(2);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node.SetId(4);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2.SetId(6);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node2.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(5);
			selector2.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3.SetId(10);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4.SetId(8);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3.SetId(3);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node3.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4.SetId(9);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node4.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(25);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node85 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node85();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5.SetId(85);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6.SetId(7);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node38 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node38();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7.SetId(38);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node39 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node39();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8.SetId(39);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node40 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node40();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9.SetId(40);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node26 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node26();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10.SetId(26);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node10.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node35 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node35();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11.SetId(35);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node29 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node29();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5.SetId(29);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(30);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12.SetId(15);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node37 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node37();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13.SetId(37);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node41 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node41();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14.SetId(41);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node11();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15.SetId(11);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node15.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node31 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node16 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node31();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node16.SetId(31);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node16);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node16.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node33 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node33();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6.SetId(33);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(27);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node17 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node12();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node17.SetId(12);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node17);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node17.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node32 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node32();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18.SetId(32);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node34 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node34();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19.SetId(34);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node36 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node36();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7.SetId(36);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(21);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node13();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20.SetId(13);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node21 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node21.SetId(22);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node21);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node21.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22.SetId(23);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node22.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8.SetId(24);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node8.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(17);
			selector.AddChild(sequence7);
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node14();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23.SetId(14);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node23.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node18();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24.SetId(18);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node24.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19 condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node25 = new Condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node19();
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node25.SetId(19);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node25);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node25.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20 action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9 = new Action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node20();
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9.SetId(20);
			sequence7.AddChild(action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_65Tuanben_Dajisi_Boss_ACTION_node9.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
