using System;

namespace behaviac
{
	// Token: 0x02002DCA RID: 11722
	public static class bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT
	{
		// Token: 0x06014473 RID: 83059 RVA: 0x00617AA4 File Offset: 0x00615EA4
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/Dashengqishi_Boss_EVENT");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node11 parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node = new Parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node11();
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetId(11);
			bt.AddChild(parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(14);
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node26 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node26();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetId(26);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node27 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node27();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2.SetId(27);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node12 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node12();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3.SetId(12);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node29 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node29();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetId(29);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node30 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node30();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2.SetId(30);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(7);
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4.SetId(9);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3.SetId(8);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node10 assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node = new Assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node10();
			assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetId(10);
			sequence2.AddChild(assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(25);
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node3();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5.SetId(3);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node36 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node36();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6.SetId(36);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node28 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node28();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4.SetId(28);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node4();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5.SetId(4);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(0);
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node1 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node1();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7.SetId(1);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node2();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8.SetId(2);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node5();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6.SetId(5);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node6();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7.SetId(6);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node7.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(15);
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.AddChild(sequence5);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node16 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node16();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9.SetId(16);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node13 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node13();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8.SetId(13);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node8.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node17 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node17();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9.SetId(17);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node9.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents() | sequence5.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_EVENT_node.HasEvents());
			return true;
		}
	}
}
