using System;

namespace behaviac
{
	// Token: 0x02003465 RID: 13413
	public static class bt_Monster_AI_Heisedadi_Hundun_Event
	{
		// Token: 0x06015116 RID: 86294 RVA: 0x00658B14 File Offset: 0x00656F14
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Heisedadi/Hundun_Event");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node3 parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node = new Parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node3();
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetId(3);
			bt.AddChild(parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.AddChild(sequence);
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetId(6);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node14 action_bt_Monster_AI_Heisedadi_Hundun_Event_node = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node14();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetId(14);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node11 action_bt_Monster_AI_Heisedadi_Hundun_Event_node2 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node11();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node2.SetId(11);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node2.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node5 action_bt_Monster_AI_Heisedadi_Hundun_Event_node3 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node5();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node3.SetId(5);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node3);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node3.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node0 action_bt_Monster_AI_Heisedadi_Hundun_Event_node4 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node0();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node4.SetId(0);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node4);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node4.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node2 action_bt_Monster_AI_Heisedadi_Hundun_Event_node5 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node2();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node5.SetId(2);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node5);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node5.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(30);
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.AddChild(sequence2);
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node31 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node2 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node31();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node2.SetId(31);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node2.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node32 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node3 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node32();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node3.SetId(32);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node3.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4.SetId(4);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node4.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node33 action_bt_Monster_AI_Heisedadi_Hundun_Event_node6 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node33();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node6.SetId(33);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node6.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node12 action_bt_Monster_AI_Heisedadi_Hundun_Event_node7 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node12();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node7.SetId(12);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node7.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node34 action_bt_Monster_AI_Heisedadi_Hundun_Event_node8 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node34();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node8.SetId(34);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node8);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node8.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node35 action_bt_Monster_AI_Heisedadi_Hundun_Event_node9 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node35();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node9.SetId(35);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node9);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node9.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node36 action_bt_Monster_AI_Heisedadi_Hundun_Event_node10 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node36();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node10.SetId(36);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node10);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node10.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(23);
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.AddChild(sequence3);
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node24 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node5 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node24();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node5.SetId(24);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node5.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node25 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node25();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6.SetId(25);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node6.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7.SetId(7);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node7.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node26 action_bt_Monster_AI_Heisedadi_Hundun_Event_node11 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node26();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node11.SetId(26);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node11.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node15 action_bt_Monster_AI_Heisedadi_Hundun_Event_node12 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node15();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node12.SetId(15);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node12);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node12.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node27 action_bt_Monster_AI_Heisedadi_Hundun_Event_node13 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node27();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node13.SetId(27);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node13);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node13.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node28 action_bt_Monster_AI_Heisedadi_Hundun_Event_node14 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node28();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node14.SetId(28);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node14);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node14.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node29 action_bt_Monster_AI_Heisedadi_Hundun_Event_node15 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node29();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node15.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node15.SetId(29);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node15);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node15.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(17);
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.AddChild(sequence4);
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node19 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node8 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node19();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node8.SetId(19);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node8.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node21 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node9 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node21();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node9.SetId(21);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node9.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10.SetId(10);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node10.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node8 action_bt_Monster_AI_Heisedadi_Hundun_Event_node16 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node8();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node16.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node16.SetId(8);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node16);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node16.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node16 action_bt_Monster_AI_Heisedadi_Hundun_Event_node17 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node16();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node17.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node17.SetId(16);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node17);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node17.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node9 action_bt_Monster_AI_Heisedadi_Hundun_Event_node18 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node9();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node18.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node18.SetId(9);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node18);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node18.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node20 action_bt_Monster_AI_Heisedadi_Hundun_Event_node19 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node20();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node19.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node19.SetId(20);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node19);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node19.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node22 action_bt_Monster_AI_Heisedadi_Hundun_Event_node20 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node22();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node20.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node20.SetId(22);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node20);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node20.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(13);
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.AddChild(sequence5);
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node39 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node11 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node39();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node11.SetId(39);
			sequence5.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node11);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node11.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node18 condition_bt_Monster_AI_Heisedadi_Hundun_Event_node12 = new Condition_bt_Monster_AI_Heisedadi_Hundun_Event_node18();
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Hundun_Event_node12.SetId(18);
			sequence5.AddChild(condition_bt_Monster_AI_Heisedadi_Hundun_Event_node12);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Heisedadi_Hundun_Event_node12.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node37 action_bt_Monster_AI_Heisedadi_Hundun_Event_node21 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node37();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node21.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node21.SetId(37);
			sequence5.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node21);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node21.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Hundun_Event_node38 action_bt_Monster_AI_Heisedadi_Hundun_Event_node22 = new Action_bt_Monster_AI_Heisedadi_Hundun_Event_node38();
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node22.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Hundun_Event_node22.SetId(38);
			sequence5.AddChild(action_bt_Monster_AI_Heisedadi_Hundun_Event_node22);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Heisedadi_Hundun_Event_node22.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents() | sequence5.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Heisedadi_Hundun_Event_node.HasEvents());
			return true;
		}
	}
}
