using System;

namespace behaviac
{
	// Token: 0x0200378A RID: 14218
	public static class bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action
	{
		// Token: 0x0601571B RID: 87835 RVA: 0x006779E8 File Offset: 0x00675DE8
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben/Chap_2_Zui_BOSS_Moxiang_Action");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7 parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node = new Parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7();
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetId(7);
			bt.AddChild(parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetId(3);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(1);
			sequence.AddChild(selector);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(6);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2.SetId(16);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node73 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node73();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3.SetId(73);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetId(8);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(5);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4.SetId(10);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node74 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node74();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5.SetId(74);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2.SetId(12);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(23);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6.SetId(24);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node75 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node75();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7.SetId(75);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3.SetId(26);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(27);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8.SetId(28);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node77 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node77();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9.SetId(77);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4.SetId(29);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(31);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10.SetId(32);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node76 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node76();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11.SetId(76);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5.SetId(33);
			sequence6.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | selector.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents() | sequence.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(11);
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.AddChild(sequence7);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12.SetId(13);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(14);
			sequence7.AddChild(selector2);
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(15);
			selector2.AddChild(sequence8);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13.SetId(17);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14.SetId(18);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6.SetId(19);
			sequence8.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node6.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(20);
			selector2.AddChild(sequence9);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15.SetId(21);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16.SetId(22);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7.SetId(25);
			sequence9.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node7.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(30);
			selector2.AddChild(sequence10);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17.SetId(34);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18.SetId(38);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8.SetId(42);
			sequence10.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node8.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(46);
			selector2.AddChild(sequence11);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node50 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node50();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19.SetId(50);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node54 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node54();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20.SetId(54);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node78 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node78();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9.SetId(78);
			sequence11.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node9.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(79);
			selector2.AddChild(sequence12);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node80 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node80();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21.SetId(80);
			sequence12.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node21.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node81 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node81();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22.SetId(81);
			sequence12.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node22.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node82 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node82();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10.SetId(82);
			sequence12.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node10.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
			sequence7.SetHasEvents(sequence7.HasEvents() | selector2.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents() | sequence7.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(2);
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.AddChild(sequence13);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node23 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node4();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node23.SetId(4);
			sequence13.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node23);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node23.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(9);
			sequence13.AddChild(selector3);
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(35);
			selector3.AddChild(sequence14);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24.SetId(36);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node24.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node83 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node83();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25.SetId(83);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node25.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11.SetId(37);
			sequence14.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node11.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(39);
			selector3.AddChild(sequence15);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26.SetId(40);
			sequence15.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node26.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node84 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node27 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node84();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node27.SetId(84);
			sequence15.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node27);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node27.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12.SetId(41);
			sequence15.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node12.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(43);
			selector3.AddChild(sequence16);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28.SetId(44);
			sequence16.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node28.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node85 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node85();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29.SetId(85);
			sequence16.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node29.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node45 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node45();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13.SetId(45);
			sequence16.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node13.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence16.HasEvents());
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(47);
			selector3.AddChild(sequence17);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node48 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node30 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node48();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node30.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node30.SetId(48);
			sequence17.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node30);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node30.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node86 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node31 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node86();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node31.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node31.SetId(86);
			sequence17.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node31);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node31.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node49 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node49();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14.SetId(49);
			sequence17.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node14.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence17.HasEvents());
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(51);
			selector3.AddChild(sequence18);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node52 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node52();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32.SetId(52);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node32.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node87 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node87();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33.SetId(87);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node33.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node53 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node53();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15.SetId(53);
			sequence18.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node15.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence18.HasEvents());
			sequence13.SetHasEvents(sequence13.HasEvents() | selector3.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents() | sequence13.HasEvents());
			Sequence sequence19 = new Sequence();
			sequence19.SetClassNameString("Sequence");
			sequence19.SetId(55);
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.AddChild(sequence19);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node56 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node56();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34.SetId(56);
			sequence19.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34);
			sequence19.SetHasEvents(sequence19.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node34.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(57);
			sequence19.AddChild(selector4);
			Sequence sequence20 = new Sequence();
			sequence20.SetClassNameString("Sequence");
			sequence20.SetId(58);
			selector4.AddChild(sequence20);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node59 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node35 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node59();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node35.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node35.SetId(59);
			sequence20.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node35);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node35.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node60 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node60();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36.SetId(60);
			sequence20.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36);
			sequence20.SetHasEvents(sequence20.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node36.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node61 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node61();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16.SetId(61);
			sequence20.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16);
			sequence20.SetHasEvents(sequence20.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node16.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence20.HasEvents());
			Sequence sequence21 = new Sequence();
			sequence21.SetClassNameString("Sequence");
			sequence21.SetId(62);
			selector4.AddChild(sequence21);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node63 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node63();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37.SetId(63);
			sequence21.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node37.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node64 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node64();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38.SetId(64);
			sequence21.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38);
			sequence21.SetHasEvents(sequence21.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node38.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node65 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node65();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17.SetId(65);
			sequence21.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17);
			sequence21.SetHasEvents(sequence21.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node17.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence21.HasEvents());
			Sequence sequence22 = new Sequence();
			sequence22.SetClassNameString("Sequence");
			sequence22.SetId(66);
			selector4.AddChild(sequence22);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node67 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node39 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node67();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node39.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node39.SetId(67);
			sequence22.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node39);
			sequence22.SetHasEvents(sequence22.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node39.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node68 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node68();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40.SetId(68);
			sequence22.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40);
			sequence22.SetHasEvents(sequence22.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node40.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node69 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node69();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18.SetId(69);
			sequence22.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18);
			sequence22.SetHasEvents(sequence22.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node18.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence22.HasEvents());
			Sequence sequence23 = new Sequence();
			sequence23.SetClassNameString("Sequence");
			sequence23.SetId(70);
			selector4.AddChild(sequence23);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node71 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node71();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41.SetId(71);
			sequence23.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node41.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node72 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node72();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42.SetId(72);
			sequence23.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42);
			sequence23.SetHasEvents(sequence23.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node42.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node88 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node88();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19.SetId(88);
			sequence23.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19);
			sequence23.SetHasEvents(sequence23.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node19.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence23.HasEvents());
			Sequence sequence24 = new Sequence();
			sequence24.SetClassNameString("Sequence");
			sequence24.SetId(89);
			selector4.AddChild(sequence24);
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node90 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node43 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node90();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node43.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node43.SetId(90);
			sequence24.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node43);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node43.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node91 condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44 = new Condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node91();
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44.SetId(91);
			sequence24.AddChild(condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44);
			sequence24.SetHasEvents(sequence24.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node44.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node92 action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20 = new Action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node92();
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20.SetId(92);
			sequence24.AddChild(action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20);
			sequence24.SetHasEvents(sequence24.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node20.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence24.HasEvents());
			sequence19.SetHasEvents(sequence19.HasEvents() | selector4.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents() | sequence19.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Tuanben_Chap_2_Zui_BOSS_Moxiang_Action_node.HasEvents());
			return true;
		}
	}
}
