using System;

namespace behaviac
{
	// Token: 0x02003AA4 RID: 15012
	public static class bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT
	{
		// Token: 0x06015D0C RID: 89356 RVA: 0x00697010 File Offset: 0x00695410
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben/KexilaXianshi_Boss_EVENT");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3 parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node = new Parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3();
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetId(3);
			bt.AddChild(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node);
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node0 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node0();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetId(0);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents());
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(87);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node90 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node90();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetId(90);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents());
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node89 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node89();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetId(89);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node91 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node91();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetId(91);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node113 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node113();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.SetId(113);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(2);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.SetId(5);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.SetId(6);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.SetId(4);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(92);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node93 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node93();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.SetId(93);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node96 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node96();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6.SetId(96);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node118 assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node = new Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node118();
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetId(118);
			sequence3.AddChild(assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node);
			sequence3.SetHasEvents(sequence3.HasEvents() | assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node114 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node114();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7.SetId(114);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node1 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node1();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8.SetId(1);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents() | sequence3.HasEvents());
			Parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node97 parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2 = new Parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node97();
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetId(97);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.AddChild(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2);
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(98);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node99 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node99();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.SetId(99);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.HasEvents());
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node88 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node88();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6.SetId(88);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node6.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node95 assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2 = new Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node95();
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetId(95);
			sequence4.AddChild(assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2);
			sequence4.SetHasEvents(sequence4.HasEvents() | assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node100 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node100();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9.SetId(100);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(101);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node102 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node102();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7.SetId(102);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node7.HasEvents());
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node111 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node111();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8.SetId(111);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node8.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node110 assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3 = new Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node110();
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.SetId(110);
			sequence5.AddChild(assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3);
			sequence5.SetHasEvents(sequence5.HasEvents() | assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node3.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node103 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node103();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10.SetId(103);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(104);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.AddChild(sequence6);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node105 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node105();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9.SetId(105);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node9.HasEvents());
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node112 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node112();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10.SetId(112);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node10.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node116 assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4 = new Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node116();
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.SetId(116);
			sequence6.AddChild(assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4);
			sequence6.SetHasEvents(sequence6.HasEvents() | assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node106 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node106();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11.SetId(106);
			sequence6.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(107);
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.AddChild(sequence7);
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node108 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node108();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11.SetId(108);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node11.HasEvents());
			Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node115 condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12 = new Condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node115();
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12.SetId(115);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node117 assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5 = new Assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node117();
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.SetId(117);
			sequence7.AddChild(assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5);
			sequence7.SetHasEvents(sequence7.HasEvents() | assignment_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node5.HasEvents());
			Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node109 action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12 = new Action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node109();
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12.SetId(109);
			sequence7.AddChild(action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node12.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents() | sequence7.HasEvents());
			parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents() | parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node2.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Tuanben_KexilaXianshi_Boss_EVENT_node.HasEvents());
			return true;
		}
	}
}
