using System;

namespace behaviac
{
	// Token: 0x02003866 RID: 14438
	public static class bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action
	{
		// Token: 0x060158B2 RID: 88242 RVA: 0x0067FEC8 File Offset: 0x0067E2C8
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben/Chap_3_Emeng_BOSS_Kexila_Action");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7 parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node = new Parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7();
			parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetId(7);
			bt.AddChild(parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetId(3);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node49 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node49();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2.SetId(49);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(1);
			sequence.AddChild(selector);
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(6);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3.SetId(16);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node50 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node50();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4.SetId(50);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetId(8);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(5);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5.SetId(10);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node52 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node52();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6.SetId(52);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2.SetId(12);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(11);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7.SetId(13);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node53 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node53();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8.SetId(53);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3.SetId(18);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(19);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9.SetId(20);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node54 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node54();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10.SetId(54);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4.SetId(22);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(23);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11.SetId(24);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node55 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node55();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12.SetId(55);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5.SetId(26);
			sequence6.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(27);
			selector.AddChild(sequence7);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13.SetId(28);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node56 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node56();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14.SetId(56);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6.SetId(29);
			sequence7.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(31);
			selector.AddChild(sequence8);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node32 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node32();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15.SetId(32);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node34 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node34();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7.SetId(34);
			sequence8.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			sequence.SetHasEvents(sequence.HasEvents() | selector.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.HasEvents() | sequence.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(9);
			parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.AddChild(sequence9);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node4();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16.SetId(4);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node16.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node51 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node51();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17.SetId(51);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(2);
			sequence9.AddChild(selector2);
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(14);
			selector2.AddChild(sequence10);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node15();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18.SetId(15);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node18.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node19 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node17();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node19.SetId(17);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node19);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node19.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8.SetId(21);
			sequence10.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node8.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(25);
			selector2.AddChild(sequence11);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20.SetId(30);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node20.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node33 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node33();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21.SetId(33);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node21.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node35 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node35();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9.SetId(35);
			sequence11.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node9.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(36);
			selector2.AddChild(sequence12);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node37 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node37();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22.SetId(37);
			sequence12.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node22.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node38 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node23 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node38();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node23.SetId(38);
			sequence12.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node23);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node23.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node39 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node39();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10.SetId(39);
			sequence12.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node10.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(40);
			selector2.AddChild(sequence13);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node41 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node41();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24.SetId(41);
			sequence13.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node24.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node42 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node25 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node42();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node25.SetId(42);
			sequence13.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node25);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node25.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node43 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node43();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11.SetId(43);
			sequence13.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node11.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence13.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(44);
			selector2.AddChild(sequence14);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node45 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node45();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26.SetId(45);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node26.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node46 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node27 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node46();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node27.SetId(46);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node27);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node27.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node47 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node47();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12.SetId(47);
			sequence14.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node12.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(48);
			selector2.AddChild(sequence15);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node57 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node57();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28.SetId(57);
			sequence15.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node28.HasEvents());
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node58 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node58();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29.SetId(58);
			sequence15.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node29.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node59 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node59();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13.SetId(59);
			sequence15.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node13.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(60);
			selector2.AddChild(sequence16);
			Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node61 condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30 = new Condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node61();
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30.SetId(61);
			sequence16.AddChild(condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node30.HasEvents());
			Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node62 action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14 = new Action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node62();
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14.SetId(62);
			sequence16.AddChild(action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node14.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence16.HasEvents());
			sequence9.SetHasEvents(sequence9.HasEvents() | selector2.HasEvents());
			parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.SetHasEvents(parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.HasEvents() | sequence9.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Tuanben_Chap_3_Emeng_BOSS_Kexila_Action_node.HasEvents());
			return true;
		}
	}
}
