using System;

namespace behaviac
{
	// Token: 0x020033A9 RID: 13225
	public static class bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action
	{
		// Token: 0x06014FAD RID: 85933 RVA: 0x0065204C File Offset: 0x0065044C
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/GoblinKingdom/Juxingbaodan_skill_Action");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node0 parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node = new Parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node0();
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetId(0);
			bt.AddChild(parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node);
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(6);
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(8);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetId(9);
			sequence.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node1 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node1();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2.SetId(1);
			sequence.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3.SetId(11);
			sequence.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4.SetId(3);
			sequence.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetId(12);
			sequence.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2 = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2.SetId(7);
			sequence.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(13);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node2();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5.SetId(2);
			sequence2.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6.SetId(4);
			sequence2.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node16 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node16();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7.SetId(16);
			sequence2.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node17 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3 = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node17();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3.SetId(17);
			sequence2.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node3.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node14 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4 = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node14();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4.SetId(14);
			sequence2.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetHasEvents(parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.HasEvents() | selector.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(19);
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.AddChild(sequence3);
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node8 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node8.SetId(10);
			sequence3.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node8.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9.SetId(5);
			sequence3.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node9.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node22 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5 = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node22();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5.SetId(22);
			sequence3.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node5.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node23 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6 = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node23();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6.SetId(23);
			sequence3.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node6.HasEvents());
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetHasEvents(parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(15);
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.AddChild(sequence4);
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node18 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node18();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10.SetId(18);
			sequence4.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node10.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node20 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node20();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11.SetId(20);
			sequence4.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node11.HasEvents());
			Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node21 condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12 = new Condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node21();
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12.SetId(21);
			sequence4.AddChild(condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node12.HasEvents());
			Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node24 action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7 = new Action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node24();
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7.SetClassNameString("Action");
			action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7.SetId(24);
			sequence4.AddChild(action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node7.HasEvents());
			parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.SetHasEvents(parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.HasEvents() | sequence4.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_GoblinKingdom_Juxingbaodan_skill_Action_node.HasEvents());
			return true;
		}
	}
}
