using System;

namespace behaviac
{
	// Token: 0x02003542 RID: 13634
	public static class bt_Monster_AI_Heisedadi_Nadeer_Event_1
	{
		// Token: 0x060152C7 RID: 86727 RVA: 0x006603DC File Offset: 0x0065E7DC
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Heisedadi/Nadeer_Event_1");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8 parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node = new Parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8();
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetId(8);
			bt.AddChild(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(1);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetId(2);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetId(48);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2.SetId(3);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(4);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence2);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2.SetId(5);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node2.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3.SetId(6);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4.SetId(7);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(0);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence3);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3.SetId(9);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node3.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5.SetId(10);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6.SetId(34);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(12);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence4);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4.SetId(13);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node4.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7.SetId(14);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8.SetId(15);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(21);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence5);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5.SetId(22);
			sequence5.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node5.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9.SetId(23);
			sequence5.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10.SetId(35);
			sequence5.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(24);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence6);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6.SetId(25);
			sequence6.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node6.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11.SetId(26);
			sequence6.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12.SetId(27);
			sequence6.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence6.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(28);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence7);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7.SetId(29);
			sequence7.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node7.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13.SetId(30);
			sequence7.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14.SetId(31);
			sequence7.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(32);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence8);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8.SetId(33);
			sequence8.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node8.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15.SetId(36);
			sequence8.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16.SetId(37);
			sequence8.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(38);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence9);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9.SetId(39);
			sequence9.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node9.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17.SetId(40);
			sequence9.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18.SetId(41);
			sequence9.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node19 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node19.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node19.SetId(42);
			sequence9.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node19);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node19.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20.SetId(43);
			sequence9.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(44);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(sequence10);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10.SetId(45);
			sequence10.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node10.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node21 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node21.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node21.SetId(46);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node21);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node21.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22.SetId(47);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node22.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23.SetId(49);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node23.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node24 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node24.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node24.SetId(50);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node24);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node24.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25.SetId(68);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node25.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node102 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node102();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26.SetId(102);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node26.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27.SetId(65);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node27.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node28 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node28.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node28.SetId(67);
			sequence10.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node28);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node28.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | sequence10.HasEvents());
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(58);
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.AddChild(selector);
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(17);
			selector.AddChild(sequence11);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11.SetId(51);
			sequence11.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node11();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12.SetId(11);
			sequence11.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node12.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29.SetId(55);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node29.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30.SetId(56);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node30.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31.SetId(57);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node31.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node32 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node32.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node32.SetId(59);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node32);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node32.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33.SetId(64);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node33.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34.SetId(66);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node34.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35.SetId(61);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node35.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36.SetId(62);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node36.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37.SetId(69);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node37.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node103 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node38 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node103();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node38.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node38.SetId(103);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node38);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node38.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39.SetId(60);
			sequence11.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node39.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence11.HasEvents());
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(19);
			selector.AddChild(sequence12);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13.SetId(52);
			sequence12.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node13.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14.SetId(16);
			sequence12.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node14.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node81 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node81();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40.SetId(81);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node40.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node82 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node82();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41.SetId(82);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node41.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node83 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node83();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42.SetId(83);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node42.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node84 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node84();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43.SetId(84);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node43.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node85 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node44 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node85();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node44.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node44.SetId(85);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node44);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node44.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node86 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node86();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45.SetId(86);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node45.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node87 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node87();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46.SetId(87);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node46.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node88 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node88();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47.SetId(88);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node47.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node89 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node89();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48.SetId(89);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node48.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node104 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node104();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49.SetId(104);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node49.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node90 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node90();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50.SetId(90);
			sequence12.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node50.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(63);
			selector.AddChild(sequence13);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15.SetId(54);
			sequence13.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node15.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16.SetId(18);
			sequence13.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node16.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51.SetId(71);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node51.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52.SetId(72);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node52.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node73 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node53 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node73();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node53.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node53.SetId(73);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node53);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node53.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node74 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node74();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54.SetId(74);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node54.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node75 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node75();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55.SetId(75);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node55.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node76 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node76();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56.SetId(76);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node56.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node77 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node77();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57.SetId(77);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node57.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node78 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node58 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node78();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node58.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node58.SetId(78);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node58);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node58.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node79 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node79();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59.SetId(79);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node59.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node105 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node105();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60.SetId(105);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node60.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node80 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node80();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61.SetId(80);
			sequence13.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node61.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence13.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(53);
			selector.AddChild(sequence14);
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17.SetId(70);
			sequence14.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node17.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20 condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18 = new Condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node20();
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18.SetId(20);
			sequence14.AddChild(condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node18.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node92 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node92();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62.SetId(92);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node62.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node93 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node63 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node93();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node63.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node63.SetId(93);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node63);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node63.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node94 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node94();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64.SetId(94);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node64.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node95 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node95();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65.SetId(95);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node65.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node96 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node96();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66.SetId(96);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node66.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node97 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node97();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67.SetId(97);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node67.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node98 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node98();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68.SetId(98);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node68.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node99 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node99();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69.SetId(99);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node69.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node100 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node100();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70.SetId(100);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node70.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node106 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node106();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71.SetId(106);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node71.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node101 action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72 = new Action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node101();
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72.SetId(101);
			sequence14.AddChild(action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node72.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence14.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents() | selector.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Heisedadi_Nadeer_Event_1_node.HasEvents());
			return true;
		}
	}
}
