using System;

namespace behaviac
{
	// Token: 0x02003441 RID: 13377
	public static class bt_Monster_AI_Heisedadi_Huimie_Event
	{
		// Token: 0x060150D0 RID: 86224 RVA: 0x00657570 File Offset: 0x00655970
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Heisedadi/Huimie_Event");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node1 parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node = new Parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node1();
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetId(1);
			bt.AddChild(parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(5);
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.AddChild(sequence);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetId(8);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetId(9);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node0 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node0();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3.SetId(0);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node2();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4.SetId(2);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node5 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node3();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node5.SetId(3);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node5);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node5.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node4();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6.SetId(4);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node6();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7.SetId(6);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node7();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8.SetId(7);
			sequence.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node8.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node25 action_bt_Monster_AI_Heisedadi_Huimie_Event_node = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node25();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetId(25);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node10 action_bt_Monster_AI_Heisedadi_Huimie_Event_node2 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node10();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetId(10);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node2.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node12 action_bt_Monster_AI_Heisedadi_Huimie_Event_node3 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node12();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node3.SetId(12);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node3);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node3.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node13 action_bt_Monster_AI_Heisedadi_Huimie_Event_node4 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node13();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node4.SetId(13);
			sequence.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node4);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node4.HasEvents());
			Assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node42 assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node = new Assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node42();
			assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetId(42);
			sequence.AddChild(assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(15);
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.AddChild(sequence2);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node16 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node16();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9.SetId(16);
			sequence2.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node9.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node14 action_bt_Monster_AI_Heisedadi_Huimie_Event_node5 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node14();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node5.SetId(14);
			sequence2.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node5.HasEvents());
			Parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node52 parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2 = new Parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node52();
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetId(52);
			sequence2.AddChild(parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(54);
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.AddChild(sequence3);
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node55 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node10 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node55();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node10.SetId(55);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node10.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node19 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node11 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node19();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node11.SetId(19);
			sequence3.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node11.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node56 action_bt_Monster_AI_Heisedadi_Huimie_Event_node6 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node56();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node6.SetId(56);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node6.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node57 action_bt_Monster_AI_Heisedadi_Huimie_Event_node7 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node57();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node7.SetId(57);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node7.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node58 action_bt_Monster_AI_Heisedadi_Huimie_Event_node8 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node58();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node8.SetId(58);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node8.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node27 action_bt_Monster_AI_Heisedadi_Huimie_Event_node9 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node27();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node9.SetId(27);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node9.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node20 action_bt_Monster_AI_Heisedadi_Huimie_Event_node10 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node20();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node10.SetId(20);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node10);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node10.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node21 action_bt_Monster_AI_Heisedadi_Huimie_Event_node11 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node21();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node11.SetId(21);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node11);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node11.HasEvents());
			DecoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node67 decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node = new DecoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node67();
			decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetClassNameString("DecoratorLoopUntil");
			decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetId(67);
			sequence3.AddChild(decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node);
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node17 action_bt_Monster_AI_Heisedadi_Huimie_Event_node12 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node17();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node12.SetId(17);
			decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node12);
			decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetHasEvents(decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node12.HasEvents());
			sequence3.SetHasEvents(sequence3.HasEvents() | decoratorLoopUntil_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node66 action_bt_Monster_AI_Heisedadi_Huimie_Event_node13 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node66();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node13.SetId(66);
			sequence3.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node13);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node13.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(53);
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.AddChild(sequence4);
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node28 action_bt_Monster_AI_Heisedadi_Huimie_Event_node14 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node28();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node14.SetId(28);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node14);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node14.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node11 action_bt_Monster_AI_Heisedadi_Huimie_Event_node15 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node11();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node15.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node15.SetId(11);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node15);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node15.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node22 action_bt_Monster_AI_Heisedadi_Huimie_Event_node16 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node22();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node16.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node16.SetId(22);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node16);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node16.HasEvents());
			Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node18 condition_bt_Monster_AI_Heisedadi_Huimie_Event_node12 = new Condition_bt_Monster_AI_Heisedadi_Huimie_Event_node18();
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Heisedadi_Huimie_Event_node12.SetId(18);
			sequence4.AddChild(condition_bt_Monster_AI_Heisedadi_Huimie_Event_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Heisedadi_Huimie_Event_node12.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node43 action_bt_Monster_AI_Heisedadi_Huimie_Event_node17 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node43();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node17.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node17.SetId(43);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node17);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node17.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node26 action_bt_Monster_AI_Heisedadi_Huimie_Event_node18 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node26();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node18.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node18.SetId(26);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node18);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node18.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node29 action_bt_Monster_AI_Heisedadi_Huimie_Event_node19 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node29();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node19.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node19.SetId(29);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node19);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node19.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node24 action_bt_Monster_AI_Heisedadi_Huimie_Event_node20 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node24();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node20.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node20.SetId(24);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node20);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node20.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node23 action_bt_Monster_AI_Heisedadi_Huimie_Event_node21 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node23();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node21.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node21.SetId(23);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node21);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node21.HasEvents());
			Action_bt_Monster_AI_Heisedadi_Huimie_Event_node51 action_bt_Monster_AI_Heisedadi_Huimie_Event_node22 = new Action_bt_Monster_AI_Heisedadi_Huimie_Event_node51();
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node22.SetClassNameString("Action");
			action_bt_Monster_AI_Heisedadi_Huimie_Event_node22.SetId(51);
			sequence4.AddChild(action_bt_Monster_AI_Heisedadi_Huimie_Event_node22);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Heisedadi_Huimie_Event_node22.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.HasEvents() | sequence4.HasEvents());
			sequence2.SetHasEvents(sequence2.HasEvents() | parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node2.HasEvents());
			parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.SetHasEvents(parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents() | sequence2.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_Heisedadi_Huimie_Event_node.HasEvents());
			return true;
		}
	}
}
