using System;

namespace behaviac
{
	// Token: 0x02002B6C RID: 11116
	public static class bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION
	{
		// Token: 0x06013FE6 RID: 81894 RVA: 0x0060033C File Offset: 0x005FE73C
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/65TB_Chuanyuezhe_ACTION");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(0);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(8);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetId(9);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetId(10);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetId(11);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(14);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetId(15);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node33 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node33();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetId(33);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetId(17);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(34);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node37 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node37();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetId(37);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node35 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node35();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetId(35);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node36 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node36();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetId(36);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(12);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node38 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node38();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7.SetId(38);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node45 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node45();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8.SetId(45);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node31 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node31();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9.SetId(31);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node30 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node30();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetId(30);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(13);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node39 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node39();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10.SetId(39);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node32 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node32();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetId(32);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			SelectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16 selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node = new SelectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16();
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetClassNameString("SelectorProbability");
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetId(16);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.Initialize("Self.BTAgent::Action_GenRandom()");
			selector.AddChild(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node);
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetId(4);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node);
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(18);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.AddChild(sequence6);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node40 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node40();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11.SetId(40);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12.SetId(19);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetId(20);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents() | sequence6.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents());
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2 = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetId(5);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(21);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.AddChild(sequence7);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node41 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node41();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13.SetId(41);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14.SetId(22);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7.SetId(23);
			sequence7.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents() | sequence7.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents());
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3 = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetId(6);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3);
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(24);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.AddChild(sequence8);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node42 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node42();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15.SetId(42);
			sequence8.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16.SetId(25);
			sequence8.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8.SetId(26);
			sequence8.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node8.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.HasEvents() | sequence8.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3.HasEvents());
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4 = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node7();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetId(7);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4);
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(27);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.AddChild(sequence9);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node43 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node43();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17.SetId(43);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node17.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node28 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node18 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node28();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node18.SetId(28);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node18);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node18.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node29 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node29();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9.SetId(29);
			sequence9.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node9.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.HasEvents() | sequence9.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node4.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(1);
			selector.AddChild(sequence10);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node44 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node44();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19.SetId(44);
			sequence10.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node19.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20.SetId(2);
			sequence10.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node20.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node3();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10.SetId(3);
			sequence10.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node10.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(46);
			selector.AddChild(sequence11);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node47 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node21 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node47();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node21.SetId(47);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node21);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node21.HasEvents());
			SelectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node48 selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2 = new SelectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node48();
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetClassNameString("SelectorProbability");
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetId(48);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.Initialize("Self.BTAgent::Action_GenRandom()");
			sequence11.AddChild(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2);
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node49 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5 = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node49();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetId(49);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5);
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(50);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.AddChild(sequence12);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node51 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node51();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22.SetId(51);
			sequence12.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node22.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node52 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node52();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11.SetId(52);
			sequence12.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node11.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.HasEvents() | sequence12.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node5.HasEvents());
			DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node53 decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6 = new DecoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node53();
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetId(53);
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.AddChild(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6);
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(54);
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.AddChild(selector2);
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(55);
			selector2.AddChild(sequence13);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node58 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node58();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23.SetId(58);
			sequence13.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node23.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node59 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node59();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12.SetId(59);
			sequence13.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node12.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence13.HasEvents());
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(60);
			selector2.AddChild(sequence14);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node61 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node24 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node61();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node24.SetId(61);
			sequence14.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node24);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node24.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node62 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node62();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13.SetId(62);
			sequence14.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node13.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence14.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(63);
			selector2.AddChild(sequence15);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node64 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node64();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25.SetId(64);
			sequence15.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node25.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node65 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node65();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14.SetId(65);
			sequence15.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14);
			sequence15.SetHasEvents(sequence15.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node14.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence15.HasEvents());
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(66);
			selector2.AddChild(sequence16);
			Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node67 condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26 = new Condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node67();
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26.SetId(67);
			sequence16.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node26.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node68 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node68();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15.SetId(68);
			sequence16.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node15.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence16.HasEvents());
			decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.SetHasEvents(decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.HasEvents() | selector2.HasEvents());
			selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.SetHasEvents(selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents() | decoratorWeight_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node6.HasEvents());
			sequence11.SetHasEvents(sequence11.HasEvents() | selectorProbability_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node69 action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16 = new Action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node69();
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16.SetId(69);
			sequence11.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Chuanyuezhe_ACTION_node16.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence11.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
