using System;

namespace behaviac
{
	// Token: 0x02002DB5 RID: 11701
	public static class bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION
	{
		// Token: 0x0601444B RID: 83019 RVA: 0x00616718 File Offset: 0x00614B18
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/Dashengqishi_Boss_ACTION");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(16);
			bt.AddChild(selector);
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(22);
			selector.AddChild(selector2);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(13);
			selector2.AddChild(sequence);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node131 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node131();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.SetId(131);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node132 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node132();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.SetId(132);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3.SetId(15);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.SetId(17);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node134 assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node = new Assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node134();
			assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.SetId(134);
			sequence.AddChild(assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node);
			sequence.SetHasEvents(sequence.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(23);
			selector2.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4.SetId(24);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5.SetId(25);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node31 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node31();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6.SetId(31);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node32 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node32();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.SetId(32);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.HasEvents());
			Assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node33 assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2 = new Assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node33();
			assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.SetId(33);
			sequence2.AddChild(assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector2.HasEvents());
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(10);
			selector.AddChild(selector3);
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(9);
			selector3.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node42 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node42();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7.SetId(42);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node34 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node34();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8.SetId(34);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9.SetId(11);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3.SetId(12);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node43 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node43();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4.SetId(43);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(26);
			selector3.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node44 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node44();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10.SetId(44);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11.SetId(27);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12.SetId(28);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5.SetId(29);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node5.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node47 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node47();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6.SetId(47);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(30);
			selector3.AddChild(sequence5);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node45 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node45();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13.SetId(45);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node35 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node35();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14.SetId(35);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node36 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node36();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15.SetId(36);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node37 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node37();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7.SetId(37);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node48 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node48();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8.SetId(48);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(38);
			selector3.AddChild(sequence6);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node46 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node16 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node46();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node16.SetId(46);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node16);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node16.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node39 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node39();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17.SetId(39);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node17.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node40 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node18 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node40();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node18.SetId(40);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node18);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node18.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node41 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node41();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9.SetId(41);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node9.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node49 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node49();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10.SetId(49);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node10.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | selector3.HasEvents());
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(14);
			selector.AddChild(sequence7);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node85 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node85();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19.SetId(85);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node53 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node53();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20.SetId(53);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node51 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node51();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21.SetId(51);
			sequence7.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node52 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node52();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11.SetId(52);
			sequence7.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node11.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(1);
			selector.AddChild(sequence8);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node22 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node2();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node22.SetId(2);
			sequence8.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node22);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node22.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node23 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node3();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node23.SetId(3);
			sequence8.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node23);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node23.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node4();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12.SetId(4);
			sequence8.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node12.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(5);
			selector.AddChild(sequence9);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node6();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24.SetId(6);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node24.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node7();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25.SetId(7);
			sequence9.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node25.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node8();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13.SetId(8);
			sequence9.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node13.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(18);
			selector.AddChild(sequence10);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node26 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node19();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node26.SetId(19);
			sequence10.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node26);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node26.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node20();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27.SetId(20);
			sequence10.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node27.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node21();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14.SetId(21);
			sequence10.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node14.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(163);
			selector.AddChild(sequence11);
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node164 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node164();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28.SetId(164);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node28.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node165 condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29 = new Condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node165();
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29.SetId(165);
			sequence11.AddChild(condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node29.HasEvents());
			Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node0 action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15 = new Action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node0();
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15.SetId(0);
			sequence11.AddChild(action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15);
			sequence11.SetHasEvents(sequence11.HasEvents() | action_bt_Monster_AI_65Tuanben_Dashengqishi_Boss_ACTION_node15.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence11.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
