using System;

namespace behaviac
{
	// Token: 0x02002C53 RID: 11347
	public static class bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event
	{
		// Token: 0x060141A2 RID: 82338 RVA: 0x00609300 File Offset: 0x00607700
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/65Tuanben/65TB_Shouhuzhe_A_Event");
			bt.IsFSM = false;
			Parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5 parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node = new Parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5();
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetClassNameString("Parallel");
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetId(5);
			bt.AddChild(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(0);
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.AddChild(sequence);
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node25 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node25();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetId(25);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node1 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node1();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetId(1);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2.SetId(3);
			sequence.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2.SetId(2);
			sequence.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node2.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(6);
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.AddChild(sequence2);
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3.SetId(7);
			sequence2.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3.SetId(8);
			sequence2.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node3.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(9);
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.AddChild(sequence3);
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4.SetId(10);
			sequence3.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4.SetId(11);
			sequence3.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(12);
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.AddChild(sequence4);
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node23 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node23();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5.SetId(23);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node4();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6.SetId(4);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node15 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node15();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7.SetId(15);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node16 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node16();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8.SetId(16);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node17 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node9 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node17();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node9.SetId(17);
			sequence4.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node9.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5.SetId(14);
			sequence4.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node5.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(18);
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.AddChild(sequence5);
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node24 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node24();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10.SetId(24);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node10.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node20 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node20();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11.SetId(20);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node11.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node21 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node12 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node21();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node12.SetId(21);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node12);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node12.HasEvents());
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node22 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node13 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node22();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node13.SetId(22);
			sequence5.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node13.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node19 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node19();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6.SetId(19);
			sequence5.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node6.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(13);
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.AddChild(sequence6);
			Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node26 condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14 = new Condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node26();
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14.SetId(26);
			sequence6.AddChild(condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node14.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node27 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node27();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7.SetId(27);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node7.HasEvents());
			Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node28 action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8 = new Action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node28();
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8.SetClassNameString("Action");
			action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8.SetId(28);
			sequence6.AddChild(action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8);
			sequence6.SetHasEvents(sequence6.HasEvents() | action_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node8.HasEvents());
			parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.SetHasEvents(parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents() | sequence6.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | parallel_bt_Monster_AI_65Tuanben_65TB_Shouhuzhe_A_Event_node.HasEvents());
			return true;
		}
	}
}
