using System;

namespace behaviac
{
	// Token: 0x02003BC2 RID: 15298
	public static class bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard
	{
		// Token: 0x06015F34 RID: 89908 RVA: 0x006A134C File Offset: 0x0069F74C
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("Monster_AI/Tuanben_hard/KexilaEmeng_Boss_ACTION_hard");
			bt.IsFSM = false;
			Selector selector = new Selector();
			selector.SetClassNameString("Selector");
			selector.SetId(3);
			bt.AddChild(selector);
			Sequence sequence = new Sequence();
			sequence.SetClassNameString("Sequence");
			sequence.SetId(64);
			selector.AddChild(sequence);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node57 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node57();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetId(57);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node50 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node50();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetId(50);
			sequence.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2);
			sequence.SetHasEvents(sequence.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node51 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node51();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetId(51);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node80 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node80();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetId(80);
			sequence.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2);
			sequence.SetHasEvents(sequence.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence.HasEvents());
			Sequence sequence2 = new Sequence();
			sequence2.SetClassNameString("Sequence");
			sequence2.SetId(44);
			selector.AddChild(sequence2);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node45 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node45();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetId(45);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node46 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node46();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetId(46);
			sequence2.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4);
			sequence2.SetHasEvents(sequence2.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node47 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node47();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetId(47);
			sequence2.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3);
			sequence2.SetHasEvents(sequence2.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.HasEvents());
			Assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node48 assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node = new Assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node48();
			assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetClassNameString("Assignment");
			assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetId(48);
			sequence2.AddChild(assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node);
			sequence2.SetHasEvents(sequence2.HasEvents() | assignment_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence2.HasEvents());
			Sequence sequence3 = new Sequence();
			sequence3.SetClassNameString("Sequence");
			sequence3.SetId(38);
			selector.AddChild(sequence3);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node39 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node39();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5.SetId(39);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node77 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node77();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6.SetId(77);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node85 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node85();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7.SetId(85);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node98 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node98();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8.SetId(98);
			sequence3.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8);
			sequence3.SetHasEvents(sequence3.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node56 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node56();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetId(56);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node40 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node40();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5.SetId(40);
			sequence3.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5);
			sequence3.SetHasEvents(sequence3.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
			Sequence sequence4 = new Sequence();
			sequence4.SetClassNameString("Sequence");
			sequence4.SetId(30);
			selector.AddChild(sequence4);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node76 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node76();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9.SetId(76);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10.SetId(31);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11.SetId(32);
			sequence4.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11);
			sequence4.SetHasEvents(sequence4.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node36 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node36();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6.SetId(36);
			sequence4.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6);
			sequence4.SetHasEvents(sequence4.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
			Sequence sequence5 = new Sequence();
			sequence5.SetClassNameString("Sequence");
			sequence5.SetId(25);
			selector.AddChild(sequence5);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node75 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node75();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12.SetId(75);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node37 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node37();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13.SetId(37);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14.SetId(26);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node5();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15.SetId(5);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16.SetId(27);
			sequence5.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16);
			sequence5.SetHasEvents(sequence5.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7.SetId(28);
			sequence5.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7);
			sequence5.SetHasEvents(sequence5.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
			Sequence sequence6 = new Sequence();
			sequence6.SetClassNameString("Sequence");
			sequence6.SetId(73);
			selector.AddChild(sequence6);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node69 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node69();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17.SetId(69);
			sequence6.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17);
			sequence6.SetHasEvents(sequence6.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17.HasEvents());
			Selector selector2 = new Selector();
			selector2.SetClassNameString("Selector");
			selector2.SetId(0);
			sequence6.AddChild(selector2);
			Selector selector3 = new Selector();
			selector3.SetClassNameString("Selector");
			selector3.SetId(2);
			selector2.AddChild(selector3);
			Sequence sequence7 = new Sequence();
			sequence7.SetClassNameString("Sequence");
			sequence7.SetId(16);
			selector3.AddChild(sequence7);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node58 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node58();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18.SetId(58);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node19 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node19.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node19.SetId(17);
			sequence7.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node19);
			sequence7.SetHasEvents(sequence7.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node19.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node18();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8.SetId(18);
			sequence7.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8);
			sequence7.SetHasEvents(sequence7.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node8.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence7.HasEvents());
			Sequence sequence8 = new Sequence();
			sequence8.SetClassNameString("Sequence");
			sequence8.SetId(4);
			selector3.AddChild(sequence8);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node6();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20.SetId(6);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node7();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21.SetId(7);
			sequence8.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21);
			sequence8.SetHasEvents(sequence8.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9.SetId(9);
			sequence8.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9);
			sequence8.SetHasEvents(sequence8.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node9.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence8.HasEvents());
			Sequence sequence9 = new Sequence();
			sequence9.SetClassNameString("Sequence");
			sequence9.SetId(33);
			selector3.AddChild(sequence9);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node22 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node22.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node22.SetId(29);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node22);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node22.HasEvents());
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node35 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node35();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23.SetId(35);
			sequence9.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23);
			sequence9.SetHasEvents(sequence9.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node34 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node34();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10.SetId(34);
			sequence9.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10);
			sequence9.SetHasEvents(sequence9.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node10.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence9.HasEvents());
			Sequence sequence10 = new Sequence();
			sequence10.SetClassNameString("Sequence");
			sequence10.SetId(13);
			selector3.AddChild(sequence10);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24.SetId(14);
			sequence10.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24);
			sequence10.SetHasEvents(sequence10.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11.SetId(15);
			sequence10.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11);
			sequence10.SetHasEvents(sequence10.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11.HasEvents());
			selector3.SetHasEvents(selector3.HasEvents() | sequence10.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | selector3.HasEvents());
			Sequence sequence11 = new Sequence();
			sequence11.SetClassNameString("Sequence");
			sequence11.SetId(8);
			selector2.AddChild(sequence11);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node49 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node25 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node49();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node25.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node25.SetId(49);
			sequence11.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node25);
			sequence11.SetHasEvents(sequence11.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node25.HasEvents());
			Selector selector4 = new Selector();
			selector4.SetClassNameString("Selector");
			selector4.SetId(1);
			sequence11.AddChild(selector4);
			Sequence sequence12 = new Sequence();
			sequence12.SetClassNameString("Sequence");
			sequence12.SetId(10);
			selector4.AddChild(sequence12);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node11();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26.SetId(11);
			sequence12.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26);
			sequence12.SetHasEvents(sequence12.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node26.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12.SetId(12);
			sequence12.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12);
			sequence12.SetHasEvents(sequence12.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node12.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | sequence12.HasEvents());
			SelectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node42 selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node = new SelectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node42();
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetClassNameString("SelectorProbability");
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetId(42);
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.Initialize("Self.BTAgent::Action_GenRandom()");
			selector4.AddChild(selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node);
			DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node41 decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node = new DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node41();
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetId(41);
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.AddChild(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node);
			Sequence sequence13 = new Sequence();
			sequence13.SetClassNameString("Sequence");
			sequence13.SetId(19);
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.AddChild(sequence13);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node20();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27.SetId(20);
			sequence13.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27);
			sequence13.SetHasEvents(sequence13.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node27.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node21();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13.SetId(21);
			sequence13.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13);
			sequence13.SetHasEvents(sequence13.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node13.HasEvents());
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetHasEvents(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents() | sequence13.HasEvents());
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetHasEvents(selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents() | decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents());
			DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node43 decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2 = new DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node43();
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetId(43);
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.AddChild(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2);
			Sequence sequence14 = new Sequence();
			sequence14.SetClassNameString("Sequence");
			sequence14.SetId(22);
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.AddChild(sequence14);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node23();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28.SetId(23);
			sequence14.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28);
			sequence14.SetHasEvents(sequence14.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node28.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node24();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14.SetId(24);
			sequence14.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14);
			sequence14.SetHasEvents(sequence14.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node14.HasEvents());
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetHasEvents(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents() | sequence14.HasEvents());
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.SetHasEvents(selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents() | decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents());
			selector4.SetHasEvents(selector4.HasEvents() | selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node.HasEvents());
			sequence11.SetHasEvents(sequence11.HasEvents() | selector4.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
			Sequence sequence15 = new Sequence();
			sequence15.SetClassNameString("Sequence");
			sequence15.SetId(52);
			selector2.AddChild(sequence15);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node53 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node53();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29.SetId(53);
			sequence15.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29);
			sequence15.SetHasEvents(sequence15.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node29.HasEvents());
			Selector selector5 = new Selector();
			selector5.SetClassNameString("Selector");
			selector5.SetId(54);
			sequence15.AddChild(selector5);
			Sequence sequence16 = new Sequence();
			sequence16.SetClassNameString("Sequence");
			sequence16.SetId(55);
			selector5.AddChild(sequence16);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node59 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node30 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node59();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node30.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node30.SetId(59);
			sequence16.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node30);
			sequence16.SetHasEvents(sequence16.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node30.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node60 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node60();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15.SetId(60);
			sequence16.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15);
			sequence16.SetHasEvents(sequence16.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node15.HasEvents());
			selector5.SetHasEvents(selector5.HasEvents() | sequence16.HasEvents());
			SelectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node61 selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2 = new SelectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node61();
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetClassNameString("SelectorProbability");
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetId(61);
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.Initialize("Self.BTAgent::Action_GenRandom()");
			selector5.AddChild(selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2);
			DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node62 decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3 = new DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node62();
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetId(62);
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.AddChild(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3);
			Sequence sequence17 = new Sequence();
			sequence17.SetClassNameString("Sequence");
			sequence17.SetId(63);
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.AddChild(sequence17);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node65 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node65();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31.SetId(65);
			sequence17.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31);
			sequence17.SetHasEvents(sequence17.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node31.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node66 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node66();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16.SetId(66);
			sequence17.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16);
			sequence17.SetHasEvents(sequence17.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node16.HasEvents());
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.SetHasEvents(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.HasEvents() | sequence17.HasEvents());
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetHasEvents(selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents() | decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node3.HasEvents());
			DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node67 decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4 = new DecoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node67();
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetClassNameString("DecoratorWeight");
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetId(67);
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.AddChild(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4);
			Sequence sequence18 = new Sequence();
			sequence18.SetClassNameString("Sequence");
			sequence18.SetId(68);
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.AddChild(sequence18);
			Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node70 condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32 = new Condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node70();
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32.SetClassNameString("Condition");
			condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32.SetId(70);
			sequence18.AddChild(condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32);
			sequence18.SetHasEvents(sequence18.HasEvents() | condition_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node32.HasEvents());
			Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node71 action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17 = new Action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node71();
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17.SetClassNameString("Action");
			action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17.SetId(71);
			sequence18.AddChild(action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17);
			sequence18.SetHasEvents(sequence18.HasEvents() | action_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node17.HasEvents());
			decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.SetHasEvents(decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.HasEvents() | sequence18.HasEvents());
			selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.SetHasEvents(selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents() | decoratorWeight_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node4.HasEvents());
			selector5.SetHasEvents(selector5.HasEvents() | selectorProbability_bt_Monster_AI_Tuanben_hard_KexilaEmeng_Boss_ACTION_hard_node2.HasEvents());
			sequence15.SetHasEvents(sequence15.HasEvents() | selector5.HasEvents());
			selector2.SetHasEvents(selector2.HasEvents() | sequence15.HasEvents());
			sequence6.SetHasEvents(sequence6.HasEvents() | selector2.HasEvents());
			selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
			bt.SetHasEvents(bt.HasEvents() | selector.HasEvents());
			return true;
		}
	}
}
